with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:952px; height:575px;\" coordsize=\"952,575\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:952px;height:575px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00D14300014711LAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:575px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:494px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CALIPER BODY<br></b>Check for scoring on<br>cylinder wall.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:342px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>OUTER PAD SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740px;top:142px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CALIPER BRACKET<br></b>Check for cracks.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:18px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>12 x 1.25 mm<br>108 N·m <br>(11.0 kgf·m, 79.6 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:161px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BRAKE <br>PADS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:80px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>WEAR INDICATOR<br></b>Install inner pad with its<br>wear indicator upward.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:373px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:204px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BLEED SCREW<br>7 N·m <br>(0.7 kgf·m, 5 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:256px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>BLEED CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:276px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CALIPER <br>PIN A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:144px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INNER PAD SHIM A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:178px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>INNER PAD SHIM B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:256px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>15 N·m <br>(1.5 kgf·m, <br>11 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:497px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTON SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:382px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTON BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:539px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:409px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>8 x 1.0 mm<br>23 N·m <br>(2.3 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:27px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Rubber grease<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:62px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>: Silicone grease<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:264px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:89px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PAD RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:17px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>CALIPER PIN B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:492px;font-weight:normal;font-size:8.68pt;\">");
write("<nobr><b>PISTON BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}