with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:879px;\" coordsize=\"950,879\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:879px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00G10500000000CAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:879px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:395px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:169px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUNLIGHT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:135px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NAVIGATION SYSTEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:271px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IRRADIATE STRENGTH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:248px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DATE<br>LONGITUDE<br>LATITUDE<br>DIRECTION OF THE VEHICLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:500px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DUAL AIR MIX CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:514px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>COOL VENT<br>DOORS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:831px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PASSENGER'S<br>AIR MIX DOORS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:815px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S<br>AIR MIX DOORS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}