with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:767px;\" coordsize=\"950,767\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:767px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA7E30E10410800000CAAD13.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:767px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:58px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:37px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>1ST<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:28px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>1ST CLUTCH/<br>1ST-HOLD CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:119px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>1ST-HOLD<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:36px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>2ND<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:36px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>2ND<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:33px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3RD CLUTCH<br>TRANSMISSION<br>FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:30px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>3RD<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:46px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>3RD<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:33px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4TH CLUTCH<br>TRANS -<br>MISSION<br>FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:25px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>4TH<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:25px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>5TH<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:55px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4TH<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:301px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE D:<br>ON (OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:137px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:123px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:120px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:163px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:135px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:119px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:120px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:134px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:138px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:113px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:113px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891px;top:162px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:184px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:258px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:216px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:306px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:310px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:310px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:328px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:333px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:346px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:469px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>A/T CLUTCH <br>PRESSURE CONTROL <br>SOLENOID VALVES<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:431px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:456px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:438px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:456px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:421px;font-weight:normal;font-size:3.50pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:519px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:553px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:566px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>MODULATOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:194px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:194px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>H7X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:229px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5N<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:229px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:197px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:316px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>A6X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:308px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>H5X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5K<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:229px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:314px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:425px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:425px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>H1X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:416px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:425px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:425px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>H3X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:348px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:348px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5N<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:348px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5R<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:348px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SC'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:381px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:356px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SHIFT<br>VALVE<br>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:380px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:380px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>8X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:457px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:453px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:427px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:424px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>4A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:461px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>CPC VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:236px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:245px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:255px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:268px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:296px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:293px;font-weight:normal;font-size:5.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:332px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:368px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:368px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>91'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:368px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>90'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:322px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LOCK-UP<br>TIMING <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:370px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:370px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:421px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:421px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:421px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>91'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:421px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:401px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LOCK-UP<br>SHIFT <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:452px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:452px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:452px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:452px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:454px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:524px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>90'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:551px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:519px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:521px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:514px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:551px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:554px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:521px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:555px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LOCK-UP<br>CONTROL <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:587px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:619px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:622px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:585px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>RELIEF VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:621px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>TORQUE <br>CONVERTER<br>CHECK <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:669px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>COOLER<br>CHECK <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:578px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:613px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:677px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:677px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:731px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>ATF<br>COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:731px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:692px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:695px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>REGULATOR<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:681px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:681px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:649px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:648px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:599px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:622px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:700px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:671px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>95'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:704px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LUBRICATION<br>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:603px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>FINAL DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:561px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LUBRICATION<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:549px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:552px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:523px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:547px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:523px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:547px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:523px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:547px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>MANUAL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:523px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:601px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:633px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:606px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:632px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>REVERSE<br>CONTROL <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:632px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:673px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:685px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:676px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:688px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:629px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:688px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:598px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:598px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:626px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:605px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SERVO <br>CONTROL <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:733px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SERVO VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:736px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>ATF PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:36px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>2ND CLUTCH<br>TRANSMISSION<br>FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:370px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:368px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:452px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:452px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:421px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>58'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:551px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:618px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:642px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>SECONDARY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:629px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:656px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>INTERMEDIARY<br>SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:616px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:523px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5R<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:552px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:601px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:601px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:601px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541px;top:697px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:602px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:348px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:348px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:263px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SHIFT<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:382px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:380px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:422px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>58'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:416px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:422px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:425px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>CPC <br>VALVE <br>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541px;top:440px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SHIFT VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:424px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:393px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598px;top:425px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:425px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>4A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:425px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>4B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:429px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>H2X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:369px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>CPC VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:379px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:385px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:419px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:385px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:283px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:275px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:256px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>REVERSE<br>CPC VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:277px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:306px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:274px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:204px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:229px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:229px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:209px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SHIFT<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:194px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SC'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:194px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:194px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:204px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:197px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:198px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:198px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:198px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:198px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:198px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:198px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:198px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:228px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:228px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:228px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5K<br></b></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:226px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>A4X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:225px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876px;top:192px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE B:<br>ON (CLOSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:273px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:256px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876px;top:234px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE C:<br>OFF (OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876px;top:277px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE A:<br>OFF (CLOSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874px;top:323px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SOLENOID<br>VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874px;top:375px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SOLENOID<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874px;top:433px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SOLENOID<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:362px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848px;top:362px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:379px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:384px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:397px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:523px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876px;top:47px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>5TH<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:225px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SHIFT <br>VALVE E<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}