with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E1RJ36200000000FEAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:69px;font-weight:normal;font-size:8.97pt;\">");
write("<nobr><b>Navi ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:68px;font-weight:normal;font-size:8.97pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:108px;font-weight:normal;font-size:8.97pt;\">");
write("<nobr><b>O K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:103px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>V-RAM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:125px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>D-RAM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:147px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>GPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:103px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>OK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:125px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>OK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:147px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>OK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:169px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:169px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>DVD-ROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:239px;font-weight:normal;font-size:8.97pt;\">");
write("<nobr><b>Mem Clear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:191px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>-<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:191px;font-weight:normal;font-size:8.33pt;\">");
write("<nobr><b>Serial No.<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}