with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:529px;\" coordsize=\"475,529\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:529px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA7E00R41100000000YDAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:529px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:17px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:42px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>I<br>Wheelhouse Lower Member <br>Point Hole 9 (0.35)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:42px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>J<br>Front Fender Upper <br>Mount Hole 9 (0.35)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:158px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:108px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:492px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>1017 (40.04)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:427px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>1065 <br>(41.93)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:318px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:183px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:494px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:186px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>K<br>Front Fender Lower <br>Mount Hole 11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:338px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:491px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}