with(document) {
write("<v:group id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/SJA7E50A20300000000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:116px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:123px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:135px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:142px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:152px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:159px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:170px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:188px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:195px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:115px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:178px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:242px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E24<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:255px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:289px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:150px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:345px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:379px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Brake pedal pressed: closed<br>Brake pedal released: open<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:473px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:371px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:387px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:426px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:443px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:132px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:196px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:260px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WEN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:370px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:379px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:388px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:396px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:409px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:427px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:419px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Brake pedal pressed: open<br>Brake pedal released: closed<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:418px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:435px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:33px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:123px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:187px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:250px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:105px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:105px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:33px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:33px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:379px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:564px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E30<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:581px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SMODE<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:607px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:623px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SUP<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:649px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:666px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SDN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:572px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:615px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:657px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:563px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:606px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:648px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:689px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:700px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:863px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:879px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SUPP<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:871px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:861px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:905px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:921px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SDNP<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:913px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:904px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:925px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:934px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:871px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:913px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:741px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT LEVER<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:974px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:415px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AC<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:415px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AD<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:473px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:177px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:287px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:995px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p10_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:1021px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:969px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:969px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:814px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p10_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:359px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:359px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}