with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00A18224000000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:78px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SIDE ENGINE MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m <br>(6.5 kgf·m, 47 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:84px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12 x 1.25 mm<br>54 N·m <br>(5.5 kgf·m, 40 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:81px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>REAR MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:81px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 x 1.25 mm<br>54 N·m <br>(5.5 kgf·m, 40 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:714px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TRANSMISSION LOWER<br>MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:699px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>FRONT MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:929px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 x 1.25 mm<br>54 N·m <br>(5.5 kgf·m, 40 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:1012px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}