with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E40J54300000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:40px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:186px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:186px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:150px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:108px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894px;top:211px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:903px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905px;top:499px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880px;top:149px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:150px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:149px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:472px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:440px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:76px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:386px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:386px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>D7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:499px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:499px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:421px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:299px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:299px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>P17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:149px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:354px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:102px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>P3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:246px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:149px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:150px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:46px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:231px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:52px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:39px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:25px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:99px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:165px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:165px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:171px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:171px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:61px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:66px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:246px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:300px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>D11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>N28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>X35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:133px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>X34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:299px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:299px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:299px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:322px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:479px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:300px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:149px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:22px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:67px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682px;top:74px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:38px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.21 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:432px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:447px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:454px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:445px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:432px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:217px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:81px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590px;top:46px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:199px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:499px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:146px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:316px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WIPER/WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:364px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>COMBINATION SWITCH <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:416px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:412px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>INTERMITTENT <br>WIPER DWELL <br>TIME <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:451px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559px;top:351px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:305px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PASSSENGER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:352px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:212px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RAIN <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:16px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>: CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:40px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:58px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:76px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>D6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:442px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:414px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:378px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:471px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:56px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.10 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:64px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:217px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:94px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>E10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:171px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:471px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>F17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:303px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:99px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:74px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.9 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:471px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:119px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>K1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:246px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:240px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:194px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:211px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:226px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>J5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>K5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>K4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>K2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:276px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>K3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:108px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:303px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:231px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:217px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:81px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:46px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:199px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:33px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:38px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.22 (BAT) (120 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:26px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:38px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:74px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>No.15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:412px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>As<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:303px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:303px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:426px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:426px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:351px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:337px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:351px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:326px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WINDSHIELD WIPER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:362px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:348px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:539px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>G203<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:471px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:471px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:198px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>CONTROL <br>BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:166px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WINDSHIELD <br>WIPER <br>MOTOR <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:419px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>WASHER FLUID <br>LEVEL SWITCH <br>(Closed : <br>Float down)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:325px;font-weight:normal;font-size:3.41pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}