with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00G10100012055KBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:19px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C LINES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:163px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SUCTION HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:522px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DISCHARGE HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:470px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C CONDENSER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:482px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:212px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:512px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:198px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:42px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:177px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:922px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:749px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:580px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:908px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C COMPRESSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:945px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Discharge hose to the A/C compressor (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:1072px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C compressor bracket to the engine block (10 x 1.25 mm): 44 N·m (4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:961px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Discharge hose to the A/C condenser (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:977px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Receiver line to the A/C condenser (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:1040px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Suction hose to the A/C compressor (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:1008px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C lines to the evaporator (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:945px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:961px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:977px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:1008px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:1024px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:1040px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:1056px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:1072px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:1056px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C compressor to the A/C compressor bracket (8 x 1.25 mm): 22 N·m (2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:1024px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C lines to the suction hose (6 x 1.0 mm): 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:416px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:384px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/C PRESSURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:269px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RECEIVER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Receiver line to the A/C pressure sensor (11 x 1.0 mm): 10.8 N·m (1.1 kgf·m, 8.0 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:992px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}