with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:336px;\" coordsize=\"475,336\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:336px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00K773000Y1841FAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:336px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:18px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>POWER TILT/TELESCOPIC<br>CONTROL UNIT CONNECTOR B (8P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:307px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:51px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:273px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>TELESCOPIC MOTOR/<br>POSITION SENSOR 8P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:129px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>TIM+ (PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:129px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>TIM− (LT GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:190px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>TIM− (LT GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:189px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>TIM+ (PNK)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}