with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E30000000000000EBA114.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:323px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:334px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:325px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:289px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:342px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:359px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:327px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>(With rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:277px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:279px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:312px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:347px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:347px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:303px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:330px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:366px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:357px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:277px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:304px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:618px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:618px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:509px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:271px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:298px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:333px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:274px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:308px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:386px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:435px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:435px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:435px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:386px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:696px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:434px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:445px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:445px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:434px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:446px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:446px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:685px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>75<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:618px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:696px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>59<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:504px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:234px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:353px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:386px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>74<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:386px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:435px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:386px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:435px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:618px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:685px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:180px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:179px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:386px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:685px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>76<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590px;top:685px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>77<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:618px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:618px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:435px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:147px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:146px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:147px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:125px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:114px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:103px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:92px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.22 (BAT) (120 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:91px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:135px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:114px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:136px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:125px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:103px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:69px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:80px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:81px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.21 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:157px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:158px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:24px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>MICU, Entry Light Control System, Trunk Lid Opener, Fuel Fill Door Opener, Keyless/Power Door Locks/Security System (Without super locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:353px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.15 (7.5 A)<br>FUSE <br>‹23−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:225px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.3 <br>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:333px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>POWER <br>SEAT <br>CONTROL <br>UNIT <br>‹19−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:324px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ADAPTIVE <br>FRONT <br>LIGHTING <br>CONTROL <br>UNIT <br>‹5−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:342px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>CONTROL <br>BLOCK <br>‹7−D› <br>‹8−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:710px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>RELAY <br>‹6−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:710px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRAKE <br>PEDAL <br>POSITION <br>SWITCH <br>‹10−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:297px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>DRIVER'S <br>MPCS <br>UNIT <br>‹16−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:271px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RAIN <br>SENSOR <br>‹6−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:333px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>DAYTIME <br>RUNNING <br>LIGHTS <br>RELAY <br>‹9−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:710px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>‹38−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:710px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>SRS UNIT <br>‹26−B› <br>‹27−B› <br>‹28−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:710px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>TRANSMISSION <br>RANGE SWITCH <br>‹37−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:276px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE <br>‹2−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:303px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>COMBINATION <br>SWITCH <br>CONTROL UNIT <br>‹7−D›<br>‹8−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:347px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>CONTROL BLOCK <br>‹7−D›<br>‹8−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:347px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL UNIT <br>‹34−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:312px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>HANDS FREE <br>TELEPHONE <br>CONTROL UNIT <br>‹25−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:279px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>POWER <br>TRUNK <br>CONTROL <br>UNIT <br>‹23−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:276px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>KEYLESS <br>CONVERTER <br>CONTROL UNIT <br>‹15−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:710px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE <br>‹4−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:288px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>COMBINATION <br>SWITCH <br>CONTROL <br>UNIT <br>‹7−D›<br>‹8−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:369px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl1_1\" name=\"prt_bl\" class=\"drag\" from=\"568,493\" to=\"567,278\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(Fuse/relay box socket)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.28pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" name=\"prt_bl\" class=\"drag\" from=\"502,493\" to=\"501,278\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(Fuse/relay box socket)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.28pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" name=\"prt_bl\" class=\"drag\" from=\"474,493\" to=\"473,278\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(Fuse/relay box socket)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.28pt;\"/>");
write("</v:line>");
write("</v:group>");
}