with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00R41100000000YDAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:75px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A, a<br>Bumper Beam Stay<br>Mount Hole 11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:75px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C, c<br>Subframe Front  <br>Mount Hole 20 (0.79) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:256px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:251px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:75px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B, b<br>Subframe Front Stay <br>Mount Hole 13 (0.51) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:823px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1010<br>(39.76)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:689px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1129 (44.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:340px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D, d<br>Subframe Rear  <br>Mount Hole 16 (0.63) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:340px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>E, e<br>Front Floor Front  <br>Point Hole 25 (0.98) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:340px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F, f<br>Front Floor Rear  <br>Point Hole 25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:204px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762px;top:529px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:538px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:555px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:566px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:504px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:478px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:254px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:768px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1031 (40.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:792px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1020<br>(40.16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:792px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1204<br>(47.40)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:901px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1676<br>(65.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:835px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>638<br>(25.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:941px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>894<br>(35.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:983px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1295 (50.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:810px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>970<br>(38.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:860px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1110<br>(43.70)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:838px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1432<br>(56.38)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:837px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1200<br>(47.24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:703px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>848 (33.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:947px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>482<br>(19.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:853px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1219<br>(47.99)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:1002px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1385<br>(54.53)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:713px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:753px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:711px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:768px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:693px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782px;top:695px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:983px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:936px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>b<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:982px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>c<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:922px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>d<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:1000px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>e<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:1004px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>f<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}