with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:577px;\" coordsize=\"475,577\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:577px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00J54400050461KBAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:577px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:19px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>: Apply primer here.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:503px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:420px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:61px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:439px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210px;top:512px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>6.5 mm<br>(0.26 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:475px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:476px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:388px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:377px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:180px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>150 mm<br>(5.91 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:181px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>1.5 mm<br>(0.059 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:193px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>150 mm<br>(5.91 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:80px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:162px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>42 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:135px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>48 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:103px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}