with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E5AH15300000000CAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:48px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Adaptive cruise control <br>(ACC) unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:370px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>VSA modulator-control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:516px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Brake actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:673px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:709px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Adaptive cruise control (ACC)<br>indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:746px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Multi-information display (MID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:773px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>CBMS indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:57px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Millimeter wave radar unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:161px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Brake lights<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:345px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Steering angle sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:396px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Wheel speed sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:447px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Master cylinder pressure<br>sensor (built into the <br>modulator unit)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:741px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>CMBS OFF switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:294px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Yaw rate sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:24px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>F-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:772px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:746px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:709px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:161px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Adaptive <br>cruise<br>control <br>(ACC) <br>relay<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:964px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>E-pretensioner unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:802px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Buzzer<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:801px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:99px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Obstacle determination<br>function<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:137px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Warning function<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:164px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>Brake control function<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:163px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:136px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:99px;font-weight:normal;font-size:8.17pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}