with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:399px;\" coordsize=\"950,399\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:399px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E30J32300041951FCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:399px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:152px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:17px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>CONNECTOR E (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:196px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>CONNECTOR P (30P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:217px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>PNK*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7px;top:217px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>BRN*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:895px;top:150px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:366px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>GRY*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:151px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:17px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>CONNECTOR H (14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:151px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:17px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>CONNECTOR W (5P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:196px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>CONNECTOR Q (14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:217px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>PNK*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:218px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>BRN*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:366px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>GRY*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:358px;font-weight:normal;font-size:8.67pt;\">");
write("<nobr><b>*1: LHD type<br>*2: RHD type<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}