with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:952px; height:837px;\" coordsize=\"952,837\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:952px;height:837px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E4RE10410600000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:837px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:711px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>3rd Clutch Transmission Fluid<br>Pressure Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:43px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Engine RPM Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:121px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Engine Coolant<br>Temperature Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:163px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Barometric Pressure<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:205px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Manifold Absolute<br>Pressure Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:247px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>ATF Temperature<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:295px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Service Check Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:331px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>SH-AWD Control Unit<br>Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:373px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>VSA Control Unit<br>Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:544px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Sequential Shift<br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:79px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Accelerator Pedal Position<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:451px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Transmission<br>Range Switch<br>Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:586px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Input Shaft (Mainshaft)<br>Speed Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:627px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Output Shaft (Countershaft)<br>Speed Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:670px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>2nd Clutch Transmission Fluid<br>Pressure Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:753px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>4th Clutch Transmission Fluid<br>Pressure Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:795px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Brake Pedal Position<br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:17px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:135px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>PGM-FI Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:307px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>A/T Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:355px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>- Ascending Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:329px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:368px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>- Descending Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:329px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:342px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Grade Logic Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:342px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:395px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Sequential Shift<br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:395px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:421px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Cruise Control<br>Downshift Request<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:421px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:507px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Clutch Pressure<br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:591px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Lock-up Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:639px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Self-diagnosis/ <br>Fail-safe Function<br>Communication and<br>Output function<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:719px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Lock Control<br>Reverse Lock Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:778px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Indicator Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:307px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Solenoid Valve A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:340px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Solenoid Valve B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:373px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Solenoid Valve C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:591px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Solenoid Valve D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:543px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>A/T Clutch Pressure<br>Control Solenoid Valve C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:508px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>A/T Clutch Pressure<br>Control Solenoid Valve B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:472px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>A/T Clutch Pressure<br>Control Solenoid Valve A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:653px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Vehicle Speed Signal<br>Data Link Connector<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:725px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift Lock Solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:767px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>A/T Gear Position Indicator<br>D Indicator<br>M Indicator<br>Shift Indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:408px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Automatic<br>5-speed<br>and<br>Reverse<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:584px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Lock-up<br>ON/OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:624px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Lock-up<br>Conditions<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:381px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>Shift-Hold Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:381px;font-weight:normal;font-size:7.71pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}