with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:385px;\" coordsize=\"475,385\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:385px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00K723000R7101FAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:385px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>EPS (LKAS) CONTROL UNIT CONNECTOR D (28P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:56px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>S2 (BRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:254px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>S4 (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:224px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>R2 (PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:199px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>S3 (BRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:356px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:105px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>S1 (PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:80px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>R1 (BLU)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}