with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA7E00H46200053401MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:21px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:21px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:44px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:43px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:148px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:112px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:214px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:178px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:286px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Front<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:286px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:215px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}