with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E30000000000000EBA105.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:477px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:357px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*2, *6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:771px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>DRIVING CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:771px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>DRIVING CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:735px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:723px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:723px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:723px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:723px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:735px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:732px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:721px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:632px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:643px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:646px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:724px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:724px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:724px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:724px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:724px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:724px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:125px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:114px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:103px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:147px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:415px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:442px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:392px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:341px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:244px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:169px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:168px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:147px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:146px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:92px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.22 (BAT) (120 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:91px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:135px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:114px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:136px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:125px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:103px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:70px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:80px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:81px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.21 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:157px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:158px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:392px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:349px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>*2, *5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:463px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:24px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>Adaptive Front Lighting System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:463px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:723px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:635px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:36px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:237px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.11 <br>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:350px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.29 (7.5 A) <br>           (10 A) <br>FUSE <br>‹32−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:415px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WINDSHIELD <br>WASHER  MOTOR <br>‹6−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:442px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>POWER REAR <br>WINDOW SUNSHADE <br>CONTROL UNIT <br>‹21−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:850px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LEFT HEADLIGHT <br>LEVELING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:850px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RIGHT HEADLIGHT <br>LEVELING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:850px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>REAR <br>LEVELING SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:850px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>FRONT<br>LEVELING SENSOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}