with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E5AH10900000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:610px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PASSENGER'S<br>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:522px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>EPS (LKAS)<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:373px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNDER-HOOD <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867px;top:303px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:176px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:113px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LKAS CAMERA<br><a href=\"javascript:CtsProc('0','000000000002322','i000')\"></b>Removal/Installation,</a><br><a href=\"javascript:CtsProc('0','000000000002323','i000')\">Adjustment (Aiming),</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:65px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LKAS CONTROL UNIT<br><a href=\"javascript:CtsProc('0','000000000002324','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE CRUISE CONTROL (ACC) UNIT<br><a href=\"javascript:CtsProc('0','000000000001277','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:96px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:145px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER-DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:206px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>POWER <br>STEERING<br>GEARBOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:268px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VSA MODULATOR-<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:957px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUXILIARY<br>UNDER-HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:790px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MILLIMETER WAVE PADAR UNIT<br><a href=\"javascript:CtsProc('0','000000000002325','i000')\"></b>Removal/Installation,</a><br><a href=\"javascript:CtsProc('0','000000000002326','i000')\">Aiming,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:885px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRAKE FLUID PRESSURE SENSOR<br><a href=\"javascript:CtsProc('0','000000000001278','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:1056px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE CRUISE CONTROL (ACC) RELAY<br><a href=\"javascript:CtsProc('0','000000000002244','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:788px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LKAS RELAY<br><a href=\"javascript:CtsProc('0','000000000002244','i000')\"></b>Test,<br></a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}