with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:176px;\" coordsize=\"475,176\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:176px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E2AH1090001242CFEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:176px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:57px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:41px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:41px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:25px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:41px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:41px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:85px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>LKAS<br>(PRESSED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:122px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>DISTANCE<br>(PRESSED)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}