with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA7E30000000000000EBA236.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:770px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:299px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>FTP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:266px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>(KE and KG model)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:266px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>(KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:457px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:445px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.33 (7.5 A) <br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-2px;top:457px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-27px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-27px;top:457px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-61px;top:513px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:457px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-60px;top:391px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:800px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:782px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:729px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:729px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-48px;top:729px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:818px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:818px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:818px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:818px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:778px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>FRONT A/F SENSOR (BANK2, SENSOR1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:446px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:457px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:256px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:729px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:646px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:646px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:729px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:879px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:818px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-241px;top:778px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>REAR A/F SENSOR (BANK1, SENSOR1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-38px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-15px;top:646px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:729px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:646px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:629px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-102px;top:646px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:757px;font-weight:normal;font-size:4.44pt;\">");
write("<nobr><b>117<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:413px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:502px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:248px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>No.4 <br>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:340px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>A/F SENSOR <br>RELAY (LAF)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-379px;top:438px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>EVAP <br>CANISTER <br>PURGE <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-307px;top:438px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ENGINE <br>MOUNT <br>CONTROL <br>SOLENOID <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-191px;top:401px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ALTERNATOR <br>‹1−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-268px;top:406px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ELD UNIT <br>‹1−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-407px;top:782px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>G101 <br>‹35−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:774px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>FRONT SECONDARY HO2S <br>(BANK2, SENSOR2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:774px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>RAER SECONDARY HO2S <br>(BANK1, SENSOR2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:774px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>EGR VALVE <br>POSITION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:774px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>EGR <br>VALVE <br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:782px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>IMT ACTUATOR <br>‹37−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:800px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>INPUT SHAFT <br>(MAINSHAFT) <br>SPEED SENSOR <br>‹37−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-46px;top:318px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>ENGINE OIL <br>LEVEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:408px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>AUXILIARY <br>UNADER−DASH <br>FUSE HOLDER2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:290px;font-weight:normal;font-size:5.28pt;\">");
write("<nobr><b>EVAP CANISTER <br>VENT SHUT VALVE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}