with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:959px;\" coordsize=\"950,959\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:959px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E30A20336335001KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:959px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UPPER COVER<br></b>Replace if it is cracked or if the<br>mating surface is damaged.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:144px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:161px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m<br>(1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:265px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>EXHAUST GAS<br>RECIRCULATION<br>(EGR) PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:335px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>EVAPORATIVE EMISSION <br>(EVAP) CANISTER <br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:508px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:709px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:770px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>THROTTLE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:813px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:868px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br>TEMPERATURE<br>(IAT) SENSOR<br>18 N·m<br>(1.8 kgf·m, 13 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:913px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:914px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:693px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br></b>Do not screw and unscrew<br>the 6 mm bolts<br>securing the upper<br>intake manifold and<br>lower intake manifold.<br>Replace if it is<br>cracked or if the<br>mating surface is damaged.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:100px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m<br>(1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:423px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:331px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}