with(document) {
write("<v:group id=\"group12\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect12\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img12\" name=\"PrtImgId\" src=\"../img/SJA7E30J54230100000EAAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p12_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:234px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:387px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:784px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:784px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:748px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:341px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:927px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Noise condenser<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:927px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:927px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:976px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:734px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk control unit (KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:720px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Fuel fill door opener solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:719px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:720px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:677px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:677px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:677px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:677px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:698px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:698px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:698px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p12_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:698px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:677px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p12_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:698px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Display unit<br></b></nobr>");
write("</p>");
write("<p id=\"p12_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:648px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:648px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p12_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:648px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:648px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:284px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inclination sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p12_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:263px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Alarm control siren<br></b></nobr>");
write("</p>");
write("<p id=\"p12_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:284px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:284px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p12_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:284px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:284px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:263px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:262px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:362px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:363px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk inside beeper (KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:748px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p12_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:630px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Except KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:512px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:513px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:491px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:491px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (LS1−)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (LS1+)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:463px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:441px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:441px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:462px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:463px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:441px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:441px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:463px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:599px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:598px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p12_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:598px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:599px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p12_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p12_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:569px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:548px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:412px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:413px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753px;top:316px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(KG model)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:341px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:341px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:191px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door outer handle light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p12_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:170px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door switch<br></b></nobr>");
write("</p>");
write("<p id=\"p12_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:149px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p12_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:127px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p12_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:106px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p12_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:56px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:34px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:35px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:56px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:56px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:56px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:191px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:170px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:149px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:127px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:106px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:56px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:34px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:856px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:820px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:784px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:784px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:263px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:34px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:1041px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p12_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:1040px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:1041px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Roof wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p12_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:997px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Dashborad wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:1041px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:1018px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:1020px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p12_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:34px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p12_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:34px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:905px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p12_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:997px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p12_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:35px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:56px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:106px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:127px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:192px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:149px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:56px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p12_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:170px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:262px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:1020px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p12_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:1018px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:1020px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:997px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:999px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:999px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p12_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:997px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:1020px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear shelf wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:1018px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:1020px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p12_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:785px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p12_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:785px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p12_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:905px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G801<br></b></nobr>");
write("</p>");
write("<p id=\"p12_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:1041px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear headrest subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:1040px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:1042px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p12_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:1026px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:1027px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:997px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643px;top:999px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:820px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:856px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:905px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G802<br></b></nobr>");
write("</p>");
write("<p id=\"p12_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:905px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G803<br></b></nobr>");
write("</p>");
write("<p id=\"p12_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:748px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51px;top:1041px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p12_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:1040px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:1020px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:1027px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Center rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:998px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power rear window sunshade <br>control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p12_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:134px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p12_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p12_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:648px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Ultrasonic sensor <br>(Buit into the roof console) (KG model)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}