with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:414px;\" coordsize=\"950,414\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:414px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00J54200034401FEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:414px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:53px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:123px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:184px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>O (LOCK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:235px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>I (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:287px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>II (ON)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:336px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>III (START)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:73px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>RED<br>(ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:73px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>WHT<br>(BAT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:74px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>WHT<br>(IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:73px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>RED<br>(ST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:73px;font-weight:normal;font-size:18.30pt;\">");
write("<nobr><b>GRN<br>(IG2)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}