with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:272px;\" coordsize=\"475,272\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:272px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA7E00A14500017625FHAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:272px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:23px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:49px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:73px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Cruise control<br>main switch (ON)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:36px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:36px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:36px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:226px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Cancel<br>(PRESSED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:36px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:36px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:111px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Cruise control<br>main switch (OFF)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:149px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Set/decel<br>(PRESSED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:188px;font-weight:normal;font-size:9.20pt;\">");
write("<nobr><b>Resume/accel<br>(PRESSED)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}