with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:561px;\" coordsize=\"475,561\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:561px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA7E00J16126700000MBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:561px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:495px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>E<br>8 x 1.25 mm<br>29 N·m (3.0 kgf·m, 22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:359px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:432px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:408px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br>8 x 1.25 mm<br>29 N·m <br>(3.0 kgf·m, <br>22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:40px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br>8 x 1.25 mm<br>29 N·m <br>(3.0 kgf·m, <br>22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:158px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>E<br>8 x 1.25 mm<br>29 N·m <br>(3.0 kgf·m, <br>22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:17px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:331px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}