with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:723px;\" coordsize=\"950,723\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:723px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/SJA7E30J54230100000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:723px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:199px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Hands Free Telephone control unit (KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:484px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Interface dial<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:427px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Dash lights brightness controller<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:370px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Turn signal/hazard relay 2 (sounder)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:313px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Trunk lid opener main switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:27px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>In−car temperature sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:142px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:142px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:84px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:84px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:170px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Accessory power socket<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:156px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Console box light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:199px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:199px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:199px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:199px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:84px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:84px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:534px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:484px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:427px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:370px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:313px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:142px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:27px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:677px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Console subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:676px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:677px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:484px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:370px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:534px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Audio unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:534px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25px;top:605px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>G504<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:427px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:313px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:142px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Cigarette lighter<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:27px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:142px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25px;top:462px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:656px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:654px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:656px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:362px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:84px;font-weight:normal;font-size:6.81pt;\">");
write("<nobr><b>Driver's seat heater switch/ <br>seat ventilation switch<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}