with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:609px;\" coordsize=\"475,609\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:609px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EERE10410400000KCAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:609px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:14px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m,<br>7.2 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:71px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>10 x 1.25 mm<br>43 N·m<br>(4.4 kgf·m,<br>32 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:343px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m<br>(6.5 kgf·m,<br>47 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:497px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>D<br>10 x 1.25 mm<br>47 N·m<br>(4.8 kgf·m,<br>35 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:527px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>14 x 1.5 mm<br>74 N·m<br>(7.5 kgf·m,<br>54 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:454px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>14 x 1.5 mm<br>74 N·m<br>(7.5 kgf·m,<br>54 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:473px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:423px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:285px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:483px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:180px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:15px;font-weight:normal;font-size:9.21pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}