with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:847px;\" coordsize=\"950,847\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:847px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFKA20326900000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:847px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:129px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELECTRICAL LOAD<br>DETECTOR (ELD)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:778px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KNOCK SENSOR<br><a href=\"javascript:CtsProc('0','000000000002568','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:719px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CRANKSHAFT POSITION<br>(CKP) SENSOR<br><a href=\"javascript:CtsProc('0','000000000002563','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9px;top:659px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CAMSHAFT POSITION<br>(CMP) SENSOR<br><a href=\"javascript:CtsProc('0','000000000002562','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:778px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ENGINE COOLANT TEMPERATURE<br>(ECT) SENSOR 2 (KD model)<br><a href=\"javascript:CtsProc('0','000000000002482','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:691px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ENGINE COOLANT TEMPERATURE<br>(ECT) SENSOR (Except KD model)<br>ENGINE COOLANT TEMPERATURE<br>(ECT) SENSOR 1 (KD model)<br><a href=\"javascript:CtsProc('0','000000000002564','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:72px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE<br>PRESSURE (MAP) SENSOR<br><a href=\"javascript:CtsProc('0','000000000002570','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>INJECTORS<br><a href=\"javascript:CtsProc('0','000000000002566','i000')\"></b>Test,</a><br><a href=\"javascript:CtsProc('0','000000000002567','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:175px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MASS AIR FLOW (MAF)<br>SENSOR/INTAKE AIR<br>TEMPERATURE (IAT)<br>SENSOR<br><a href=\"javascript:CtsProc('0','000000000002571','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}