with(document) {
write("<v:group id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/SJA9EFAA20300000000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:81px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:122px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PSP SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:155px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G203<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:78px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:435px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:80px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:295px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E22<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:314px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SLS<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:426px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:445px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VSSOUT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:376px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:297px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:344px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT LOCK <br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:213px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:316px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:324px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:305px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:89px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:435px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:358px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:390px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:390px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:390px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:435px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:459px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:558px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:577px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:596px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:604px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:565px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:583px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:583px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:603px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:564px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:45px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>20P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:326px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:575px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:594px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>OILLVL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:632px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:558px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:577px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:597px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:603px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:686px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:677px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:702px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727px;top:710px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:783px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BA<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:617px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:584px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:839px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*3: With EPS<br>*4: Without EPS<br>*5: With seat heater<br>*6: With ventilated seat<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:459px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To ECPS CONTROL UNIT*4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:624px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ENGINE OIL<br>LEVEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:735px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AUXILIARY<br>UNDER-DASH<br>FUSE HOLDER<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:674px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>No. 33 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:515px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:98px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PSPSW*9<br>EPSLD*8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:326px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:213px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6*5<br>5*6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:306px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:266px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>EPS CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:236px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:228px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:37px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:886px;top:196px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:481px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To EPS CONTROL UNIT*3<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}