with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFKA32200000000DAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:152px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MAIN BEARING CAPS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:357px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MAIN BEARINGS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:242px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CRANKSHAFT<br><a href=\"javascript:CtsProc('0','000000000003494','i000')\"></b>Removal,</a><br><a href=\"javascript:CtsProc('0','000000000003495','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:431px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>THRUST WASHERS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:747px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRAIN BOLT<br><a href=\"javascript:CtsProc('0','000000000000065','i000')\"></b>Installation,</a><br> in the Shop Manual, P/N 62SJA00A<br></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:580px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DOWEL PINS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:1045px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRAIN BOLT<br><a href=\"javascript:CtsProc('0','000000000000065','i000')\"></b>Installation,</a><br> in the Shop Manual, P/N 62SJA00A<br></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:535px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OIL JET BOLTS<br><a href=\"javascript:CtsProc('0','000000000000077','i000')\"></b>Inspection,</a><br> in the Shop Manual, P/N 62SJA00A<br></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:598px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>OIL JETS<br><a href=\"javascript:CtsProc('0','000000000000076','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SJA00A<br>Do not reuse oil jet, after removing it.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}