with(document) {
write("<v:group id=\"group11\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:859px;\" coordsize=\"950,859\">");
write("<v:rect id=\"rect11\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:859px;\">");
write("<img id=\"img11\" name=\"PrtImgId\" src=\"../img/SJA9EFKJ54230100000EAAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:859px;border-color:#ffffff\">");
write("<p id=\"p11_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:695px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G653<br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:424px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:424px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (RS1−)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (RS1+)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:396px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:374px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:374px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:396px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:396px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:374px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:374px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:396px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:495px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:801px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:803px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear differential subharness B<br></b></nobr>");
write("</p>");
write("<p id=\"p11_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Active noise control subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p11_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:780px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:780px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p11_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:803px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Floor subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p11_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:801px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:803px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p11_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear fog light (Except KD, KY models)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:224px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:224px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:224px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Stereo amplifier<br></b></nobr>");
write("</p>");
write("<p id=\"p11_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:246px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:246px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:246px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:246px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:246px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SH−AWD control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p11_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:274px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:274px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:274px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SH−AWD relay<br></b></nobr>");
write("</p>");
write("<p id=\"p11_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:546px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Active noise cancellation front microphone<br></b></nobr>");
write("</p>");
write("<p id=\"p11_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:560px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Active noise cancellation rear microphone<br></b></nobr>");
write("</p>");
write("<p id=\"p11_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:196px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:196px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p11_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:174px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p11_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:588px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:588px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear right side seat belt buckle switch<br></b></nobr>");
write("</p>");
write("<p id=\"p11_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:588px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear left seat belt buckle switch<br></b></nobr>");
write("</p>");
write("<p id=\"p11_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:603px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear center seat belt buckle switch<br></b></nobr>");
write("</p>");
write("<p id=\"p11_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:260px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SH−AWD control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p11_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:296px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SH−AWD control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p11_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:296px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:296px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:296px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:296px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:346px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:346px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear differential<br></b></nobr>");
write("</p>");
write("<p id=\"p11_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:546px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:546px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Active noise cancellation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p11_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:546px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:710px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Fuel pump control module<br></b></nobr>");
write("</p>");
write("<p id=\"p11_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:710px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p11_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:710px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:759px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G654<br></b></nobr>");
write("</p>");
write("<p id=\"p11_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:656px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Except KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:803px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p11_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:801px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:803px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p11_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p11_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:780px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:781px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:318px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:546px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AV<br></b></nobr>");
write("</p>");
write("<p id=\"p11_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:782px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AV<br></b></nobr>");
write("</p>");
write("<p id=\"p11_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:803px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:824px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p11_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:823px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p11_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:824px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p11_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:95px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:117px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p11_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:117px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:117px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p11_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:131px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Back−up light (KD, KY models)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p11_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:429px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p11_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:122px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p11_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:196px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Trunk lid outer handle switch <br>(Except KD model)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}