with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:588px;\" coordsize=\"950,588\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:588px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFJJ10300000000CAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:588px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:357px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:203px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:289px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUDIO DISPLAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:35px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SPEAKERS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:160px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:160px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(GA−NET)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:215px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:217px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(AUDIO−BUS)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:268px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(GA−NET)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:393px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>USB JACK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:396px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(GA−NET)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:519px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:391px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>NAVI <br>VOICE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:469px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Outputs <br>1.Audio voice prompts/guidance <br>2.Voice control (Climate audio <br>  AM−FM on GA−NET bus) <br>3.Color signal for display unit <br>4.RDS−TMC ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:280px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>ACTIVE SOUND <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:210px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>FACTORY AUDIO <br>ACCESSORY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:97px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>RADIO <br>REMOTE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:90px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>ANTENNA <br>MODULE <br>UNIT AMP <br>(AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:89px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>AUIDO AMP <br>(PREMIUM <br>SOUND <br>SYSTEM)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:96px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HANDS FREE <br>TELEPHONE <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:318px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>USB ADAPTER <br>UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}