with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/SJA9EEAA20300000000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:621px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:637px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VSB1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:619px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:629px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:881px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>REAR SECONDARY HO2S <br>(BANK 1, SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:813px;top:581px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>REAR A/F SENSOR<br>(BANK 1, SENSOR 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:1018px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:1046px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:457px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:530px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:523px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:551px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:543px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:780px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>FRONT A/F SENSOR<br>(BANK 2, SENSOR 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:669px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:662px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:689px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:682px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:710px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:702px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:730px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:723px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:751px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:743px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:963px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:1029px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:1011px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:994px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:977px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:820px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:811px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:833px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:826px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:848px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:840px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:862px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:855px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:919px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:912px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:934px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:927px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:949px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:941px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:956px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:982px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>FRONT SECONDARY HO2S <br>(BANK 2, SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:773px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p7_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:397px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:285px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:278px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:302px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p7_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:316px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ALTL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:310px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:302px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:327px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p7_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:341px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ALTF<br></b></nobr>");
write("</p>");
write("<p id=\"p7_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:334px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:327px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:351px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p7_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:365px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ALTC<br></b></nobr>");
write("</p>");
write("<p id=\"p7_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:359px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:352px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:489px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:482px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:510px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:502px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:40px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:55px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PCS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:90px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p7_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:163px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ENGINE MOUNT<br>CONTROL SOLENOID<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p7_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:181px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:48px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:41px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:73px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:66px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:121px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:114px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:146px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:139px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:177px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p7_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:212px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:113px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:127px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>MCS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:1054px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:1024px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p7_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:1036px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:1024px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:1065px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AO<br></b></nobr>");
write("</p>");
write("<p id=\"p7_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:389px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p7_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:388px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p7_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:178px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:192px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VBSOL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:456px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:470px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AFSHTCB1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:483px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:497px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AFSHTCB2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:510px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:524px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SO2SHTCB1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:537px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:551px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SO2SHTCB2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:536px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:508px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p7_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:481px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p7_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:454px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p7_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:388px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AC<br></b></nobr>");
write("</p>");
write("<p id=\"p7_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:310px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:335px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:359px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:48px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:121px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:186px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:285px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:301px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:324px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:350px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:244px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:197px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p7_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:173px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p7_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:109px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:37px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:544px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:518px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:463px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:490px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:464px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:1036px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:773px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p7_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:719px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p7_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:733px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IPB1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:746px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p7_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:760px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VCENTB1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:772px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p7_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:744px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:717px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p7_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:725px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:753px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:782px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:874px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:892px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHO2SB1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:975px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p7_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:993px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHO2SB2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:924px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p7_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:938px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VCENTB2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:848px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p7_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:862px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IPB2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:789px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VSB2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:855px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:982px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:931px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:973px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p7_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:921px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p7_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:873px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:846px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p7_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:882px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:185px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:210px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:160px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:194px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:427px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:998px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:998px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:23px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:157px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:389px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p7_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:596px;font-weight:normal;font-size:5.23pt;\">");
write("<nobr><b>33P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:883px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}