with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EERJ00020400000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:99px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:85px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:125px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:125px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:113px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:137px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:225px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:109px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 22 (BAT) (120 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:109px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:209px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 23 (P/W) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:109px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 21 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:209px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 25 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:1060px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:159px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:175px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:159px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:259px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 26 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>X35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>X34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:306px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N1 [N6]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:227px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>J10 [J15]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:196px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:446px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:392px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:292px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>POWER TILT/TELESCOPIC STEERING SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:420px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TILT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:420px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TELESCOPIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:510px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:456px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:456px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:456px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:456px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:456px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>L3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>L1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>L2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SW GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VMP1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VMP2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VBU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:603px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:718px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:717px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:689px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:689px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:689px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TESB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TESA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:746px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TIM−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TIM+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:689px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SEG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:746px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:689px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:689px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TISA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TISB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:770px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:718px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:718px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TEM−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>TEM+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:925px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:925px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:906px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:906px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:932px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:932px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:1060px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:663px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:642px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:618px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>POWER TILT/TELESCOPIC STEERING CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:570px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:592px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BUS LOCAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:457px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>[LT GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:457px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>[LT GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:113px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:163px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>D6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:213px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:113px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:163px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:213px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:125px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:113px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:113px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:32px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:32px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:32px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:46px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776px;top:46px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:74px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:85px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>POWER <br>SEAT <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:906px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>POWER TELESCOPIC <br>MOTOR/POSITION <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:907px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>POWER TILT MOTOR/<br>POSITION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:88px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}