with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFJ000000000000EBA204.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER SWITCH (28−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STEREO AMPLIFIER (31−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E−PRETENSIONER UNIT (26−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR WINDOW SWITCH (17−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S DOOR MULTIPLEX CONTROL UNIT (18−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT HEATER SWITCH (28−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:560px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S DOOR MULTIPLEX CONTROL UNIT (18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL FILL DOOR OPENER SOLENOID (15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:729px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT WASHER MOTOR (21−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT CUSHION FAN MOTORS (29−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT BACK FAN MOTORS (29−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT−BACK HEATER (29−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:534px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT CUSHION HEATER (29−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:525px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT BACK FAN MOTORS (29−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT CUSHION FAN MOTORS (29−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC UNIT (23−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:385px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-136px;top:489px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT CUSHION HEATER (29−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E−PRETENSIONER UNIT (26−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT POSITION LIGHT (19−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:312px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:675px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT VENTILATION SWITCH LIGHT (29−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:733px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:675px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GLOVE BOX LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:636px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT (32−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:556px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER SWITCH LIGHT (28−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT ASHTRAY LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONSOLE BOX LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:423px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SELECT/RESET/INFORMATION SWITCH (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/T GEAR POSITION INDICATOR PANEL LIGHT (9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:618px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT (Light) (30−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:627px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (31−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER MIRROR SWITCH LIGHT (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:733px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:733px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (ETCSRLY) (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CABLE REEL (Steering switches lights) (23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:395px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:675px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>THROTTLE ACTUATOR CONTROL MODULE (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAZARD WARNING SWITCH LIGHT (19−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LICENSE PLATE LIGHTS (19−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE LIGHTER LIGHT (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT WASHER SWITCH LIGHT (21−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT/RIGHT REAR SEAT HEATER SWITCH LIGHT (28−C, D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:263px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:627px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:395px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:636px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:556px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:405px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:423px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:618px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:600px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:582px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:627px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:223px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH−AWD RELAY (25−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-142px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONTROL MOTOR RELAY (30−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:711px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>78<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:654px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>87<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:290px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>125<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:312px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>148<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:343px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>149<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:374px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>150<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>151<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:676px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>152<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:734px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>153<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:449px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH (23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION VOICE CONTROL SWITCH (23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT−VOICE CONTROL SWITCH (23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-514px;top:169px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 22 (70 A) <br>(AS F/B) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-355px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL FILL <br>DOOR OPEN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-355px;top:694px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:263px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:685px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY 1 <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:641px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>THROTTLE ACTUATOR <br>CONTROL MODULE <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>SEAT VENTILATION CONTROL UNIT (29−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:600px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>SEAT VENTILATION SWITCH LIGHT (29−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>SEAT HEATER SWITCH LIGHT (28−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:627px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 (15 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AFS OFF/VSA OFF/<br>CMBS OFF SWITCH LIGHT (13−A) (24−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:450px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS BRIGHTNESS <br>CONTROLLER LIGHTS (13−D)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}