with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA302.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:78px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:71px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:71px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:78px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:78px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:70px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KK, KY models<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:85px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>With power trunk<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:148px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:232px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:263px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:276px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:383px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:161px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:436px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:392px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:525px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TRUNK LIGHTS (20−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:383px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:151px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 32 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 9 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:306px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:373px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEY INTERLOCK SOLENOID (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:445px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:454px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:154px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC RELAY (2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (32−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT (33−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:463px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR FOOTWELL LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:276px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:808px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:799px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 8 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:801px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:559px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:775px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:613px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:751px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S MPCS UNIT (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEYLESS CONVERTER UNIT (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:782px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:596px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:729px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER TRUNK CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:720px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER SEAT CONTROL UNIT (27−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:578px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:151px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:266px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:306px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:372px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:559px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:798px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACCESSORY POWER SOCKET (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:400px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VANITY MIRROR LIGHTS (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:383px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ROOF CONSOLE (20−A) (22−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:392px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR MAP LIGHTS (20−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:418px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR WINDOW SWITCH (17−C) (20−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:436px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S FOOTWELL LIGHT (20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S FOOTWELL LIGHT (20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:463px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR DOOR COURTESY LIGHT (20−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:471px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR DOOR INNER HANDLE LIGHT (20−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:454px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TRUNK LIGHTS (20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:445px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR FOOTWELL LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:445px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:444px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:525px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR DOOR COURTESY LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR DOOR INNER HANDLE LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR WINDOW SWITCH (17−D) (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:547px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION KEY LIGHT (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:613px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEYLESS RECEIVER UNIT (16−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE (12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:596px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:649px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT (33−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IMOES UNIT (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:578px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IMMOBILIZER CONTROL UNIT−RECEIVER (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:622px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMBINATION SWITCH CONTROL UNIT (22−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:631px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:729px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:720px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:711px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:729px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:729px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(30−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:122px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:237px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:162px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>89<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:206px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:277px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:317px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:339px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:361px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:383px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:419px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:485px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:516px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>98<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:547px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:570px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>100<br></b></nobr>");
write("</p>");
write("<p id=\"p3_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:667px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>101<br></b></nobr>");
write("</p>");
write("<p id=\"p3_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:689px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>102<br></b></nobr>");
write("</p>");
write("<p id=\"p3_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:712px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>103<br></b></nobr>");
write("</p>");
write("<p id=\"p3_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:751px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p3_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:782px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p3_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:809px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>105<br></b></nobr>");
write("</p>");
write("<p id=\"p3_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:210px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 15 (40 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (ACC) <br>(2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:202px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACCESSORY <br>POWER SOCKET <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:309px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INSIDE TRUNK LID SWITCH <br>(With power trunk) (30−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:631px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER TILT/TELESCOPIC STEERING CONTROL UNIT <br>(26−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:749px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:277px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE LIGHTER <br>(Without cigarette lighter) (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:298px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:613px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:596px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:578px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:352px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:538px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (MRLY) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (IG1) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (AFSHTCR) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:210px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FUEL PUMP CONTROL MODULE (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:192px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IMOES UNIT (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:130px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POP−UP HOOD (PUH) UNIT (26−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:715px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:755px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:746px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:613px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 IGNITION COIL (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:604px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 IGNITION COIL (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:596px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4 IGNITION COIL (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:587px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3 IGNITION COIL (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:578px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 IGNITION COIL (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 IGNITION COIL (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR SEAT HEATER RELAY (28−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:755px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ASPIRATOR FAN (31−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:746px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT (31−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:480px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:463px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:445px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:298px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CKP SENSOR A/B (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CMP SENSOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:361px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6 INJECTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:352px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 INJECTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4 INJECTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3 INJECTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 INJECTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 INJECTOR (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (IGP) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:241px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (IMOFPR) (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:192px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:174px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-442px;top:370px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 19 (40 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-324px;top:183px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN RELAY 2 <br>(FUEL PUMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-370px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY 1 <br>(IG MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-311px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/F SENSOR <br>RELAY (LAF)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-311px;top:508px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION <br>COIL RELAY <br>(IG COIL)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:175px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IMMOBILIZER CONTROL UNIT−RECEIVER <br>(11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:380px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIATOR FAN CONTROL (RFC) UNIT RELAY <br>(31−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:445px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT A/F SENSOR <br>(Bank 2, Sensor 1) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:463px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT SHO2S <br>(Bank 2, Sensor 2) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:481px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR A/F SENSOR <br>(Bank 1, Sensor 1) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-78px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR SHO2S <br>(Bank 1, Sensor 2) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:624px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:516px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EVAP CANISTER VENT SHUT VALVE <br>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-447px;top:650px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (IG2) <br>(2−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:766px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-85px;top:794px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX <br>(1−B)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}