with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:959px;\" coordsize=\"950,959\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:959px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/SJA9EFAA20300000000DBAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:959px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:94px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:141px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:193px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:848px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:819px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:563px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:791px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:563px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848px;top:543px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:573px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:616px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:595px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:679px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:563px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:538px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:538px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:538px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:487px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861px;top:259px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:305px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868px;top:429px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:460px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:31px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DASHBOARD WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:915px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}