with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:767px;\" coordsize=\"950,767\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:767px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EERE10410800000CAAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:767px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:388px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:419px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>H1X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:277px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5K<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:269px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:301px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>H5X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:309px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>A6X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:255px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SHIFT<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:200px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SHIFT<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:191px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:191px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:190px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:199px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:221px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:221px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5J<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:221px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5K<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:192px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:192px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:192px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:192px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:192px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>5G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:221px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SHIFT<br>VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:197px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:187px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:187px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>H7X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:190px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:222px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:222px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:222px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:222px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5N<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:222px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:190px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:190px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>SC'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:188px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:250px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>REVERSE<br>CPC VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:268px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:307px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:299px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:269px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:361px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>CPC VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:378px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:412px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:409px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:378px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:371px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:418px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>CPC<br>VALVE<br>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:386px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:420px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:416px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:351px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>SHIFT<br>VALVE<br>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:341px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:372px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>8X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:372px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:372px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:374px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:341px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SC'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:341px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5R<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:341px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:341px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:341px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5N<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:375px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:446px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:409px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:450px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:458px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>CPC VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:314px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LOCK-UP<br>TIMING<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:363px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:360px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:360px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>91'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:360px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:360px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>90'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:326px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:363px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:363px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:394px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LOCK-UP<br>SHIFT<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:414px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:414px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:414px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>91'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:414px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:414px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:445px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:445px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:445px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:445px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:445px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:447px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:445px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:549px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>LOCK-UP<br>CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:545px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:516px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:507px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:516px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>90'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:548px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:545px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:545px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:615px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:612px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:611px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:579px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:622px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>RELIEF<br>VALVE <br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:609px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:571px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:670px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:670px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:612px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br>CHECK<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:662px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>COOLER<br>CHECK<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:516px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>5R<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:542px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:546px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:546px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:539px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>MANUAL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:539px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:539px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:601px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:593px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:593px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:593px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:593px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:624px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:626px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:591px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:622px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:619px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:688px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>REGULATOR<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:674px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:674px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:642px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:641px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:697px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:615px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:697px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>LUBRICATION<br>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:725px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>ATF COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:725px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:685px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:728px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SERVO VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:728px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>ATF PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:690px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:666px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>4'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:672px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:681px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:681px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:683px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:546px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>MODULATOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:513px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:545px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:187px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE B:<br>ON (CLOSED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:229px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE C:<br>OFF (OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:272px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE A:<br>OFF (CLOSED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:178px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:253px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:264px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:297px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:221px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:210px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:316px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SOLENOID<br>VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:367px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SOLENOID<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:427px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SOLENOID<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:304px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:304px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:339px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:328px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:320px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:371px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:430px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:449px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:390px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:379px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:424px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:355px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:355px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:449px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:458px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>A/T CLUTCH<br>PRESSURE CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:415px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:248px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:239px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:285px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:288px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:266px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:225px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:116px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:114px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:113px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:130px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:110px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:154px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:110px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:131px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:113px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:129px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:154px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:130px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:47px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:27px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>1ST<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:20px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>1ST CLUTCH/<br>1ST-HOLD CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:113px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>1ST-HOLD<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:32px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>2ND<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:26px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>2ND<br>CLUTCH <br></b></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:22px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>3RD<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:40px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>3RD<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:52px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>4TH<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:17px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>5TH<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:17px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>4TH<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875px;top:45px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>5TH<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:28px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>3RD CLUTCH<br>TRANSMISSION<br>FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:220px;font-weight:normal;font-size:3.50pt;\">");
write("<nobr><b>A4X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:219px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>5L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:664px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>95'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:30px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>2ND CLUTCH<br>TRANSMISSION<br>FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:34px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>4TH CLUTCH<br>TRANS-<br>MISSION<br>FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:591px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:591px;font-weight:normal;font-size:4.14pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:594px;font-weight:normal;font-size:3.18pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:626px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>REVERSE<br>CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:594px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SERVO<br>CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:638px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>INTERMEDIARY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:627px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>SECONDARY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:616px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:605px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:595px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>FINAL DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:435px;font-weight:normal;font-size:5.09pt;\">");
write("<nobr><b>SHIFT VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:416px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>5F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:423px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>H2X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:425px;font-weight:normal;font-size:3.82pt;\">");
write("<nobr><b>H3X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:416px;font-weight:normal;font-size:4.77pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:293px;font-weight:normal;font-size:5.41pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE D: ON (OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:558px;font-weight:normal;font-size:4.46pt;\">");
write("<nobr><b>LUBRICATION<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}