with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EE8J54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:705px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1<br>(FI MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:681px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TURN SIGNAL/HAZARD RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:715px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACCESSORY POWER SOCKET RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:778px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MICU<br>(Built into the driver's <br>under-dash fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:989px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:1050px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STARTER CUT RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:1075px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/F SENSOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:1027px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br>(FUEL PUMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:787px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IGNITION COIL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:83px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KEYLESS CONVERTER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:34px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE FRONT LIGHTING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:82px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELECTRONICALLY CONTROLLED<br>POWER STEERING (ECPS) CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}