with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFAJ54200000000DEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:16px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LKAS CAMERA/CONTROL UNIT<br>(With LKAS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:175px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE CRUISE<br>CONTROL (ACC) UNIT<br>(With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:316px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUXILIARY<br>UNDER-DASH<br>FUSE HOLDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:628px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:685px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1<br>(FI MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:685px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TURN SIGNAL/<br>HAZARD RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:652px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACCESSORY POWER SOCKET RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:811px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MICU<br>(Built into the driver's <br>under-dash fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:972px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:1059px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STARTER CUT RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:1059px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/F SENSOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:996px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br>(FUEL PUMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:740px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IGNITION COIL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:603px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>POWER TILT/TELESCOPIC<br>STEERING CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:39px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IMMOBILIZER CONTROL<br>UNIT-RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:94px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KEYLESS CONVERTER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:130px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE FRONT LIGHTING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}