with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/SJA9EE8A20300000000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:689px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E25<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:704px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IMOCD<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:696px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:697px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To IMMOBILIZER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:320px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:342px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:363px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:383px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:522px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>TRANSMISSION RANGE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:405px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B23<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:420px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATPN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:458px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:473px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATPD<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:506px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C18<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:521px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATPS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:554px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C19<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:569px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATP<br>FWD<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:603px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>C21<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:617px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATP<br>RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:600px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:552px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:504px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:455px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:332px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:311px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:412px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:466px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:513px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:610px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:562px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:529px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/<br>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:607px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:478px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:558px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:300px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:292px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:321px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:312px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:342px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:333px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:363px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:355px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:385px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:376px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:405px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:397px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:439px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:468px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:460px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:491px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:482px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826px;top:614px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:618px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:601px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:634px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:673px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:674px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:623px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:640px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:138px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ECT SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:319px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:341px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:332px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:311px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:143px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:223px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:223px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:231px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D13<br></b></nobr>");
write("</p>");
write("<p id=\"p9_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:246px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATPP<br></b></nobr>");
write("</p>");
write("<p id=\"p9_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:279px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D16<br></b></nobr>");
write("</p>");
write("<p id=\"p9_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:294px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ATPR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:238px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:401px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p9_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:286px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:356px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:298px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:298px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:89px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p9_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:104px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ECT2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:107px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:163px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:73px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:447px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:893px;top:31px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:281px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:281px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:490px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:571px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:634px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:439px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:287px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:116px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:108px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p9_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p9_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:56px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>34P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:116px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:108px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:57px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:421px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p9_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:822px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*1: KD model<br></b></nobr>");
write("</p>");
write("<p id=\"p9_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:117px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:239px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:405px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}