with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA210.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:795px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-57px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-25px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-89px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:4px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-232px;top:807px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REAR A/F SENSOR (BANK1, SENSOR1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:839px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:884px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-17px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:684px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-89px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:603px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:508px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>APP SENSOR A/B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-64px;top:807px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT A/F SENSOR (BANK2, SENSOR1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:839px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:839px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:839px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:839px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:777px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:815px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:830px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:640px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:522px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FTP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:648px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:522px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:522px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-83px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-35px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-47px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-12px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AFSHTCR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSV<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FTP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VCC4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>APSB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:659px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SG3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:673px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>APSA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:828px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:788px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-89px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VCENTB2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IPB2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-21px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSB2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AFSHTCB2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHO2SB2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SO2SHTCB2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHO2SB1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SO2SHTCB1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EGRP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EGR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:695px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ATFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:708px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-44px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>304<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-8px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>305<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>80<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>81<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>232<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>233<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>82<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:595px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:519px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/F SENSOR RELAY (LAF) <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-337px;top:598px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EVAP <br>CANISTER <br>PURGE <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-279px;top:597px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ENGINE <br>MOUNT <br>CONTROL <br>SOLENOID <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-62px;top:559px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ALTERNATOR <br>(9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-229px;top:563px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ELD <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:805px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT SECONDARY HO2S <br>(BANK2, SENSOR2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:805px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RAER SECONDARY HO2S <br>(BANK1, SENSOR2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:805px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EGR VALVE <br>POSITION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:805px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EGR <br>VALVE <br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:816px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IMT ACTUATOR <br>(11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:829px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INPUT SHAFT (MAINSHAFT) <br>SPEED SENSOR <br>(11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598px;top:802px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ATF <br>TEMPERATURE <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:515px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EVAP CANISTER <br>VENT SHUT VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:519px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/F SENSOR RELAY (LAF) <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-370px;top:490px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 18 (15 A) <br>FUSE  <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-229px;top:479px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ELD <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:346px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PUR]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:303px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:184px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:262px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[LT BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:152px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:170px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:382px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PUR]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:254px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:196px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:177px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:191px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:205px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-103px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STRLD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJ6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJ5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJ4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJ3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJ2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INJ1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:291px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:346px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[BLU/YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:338px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:393px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:74px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:74px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:74px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:91px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:163px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:74px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NEP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OPSW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VTS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGPLS6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGPLS5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGPLS4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGPLS3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGLS2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:313px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGPLS1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:327px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-28px;top:93px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:219px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>118<br></b></nobr>");
write("</p>");
write("<p id=\"p2_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:121px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>265<br></b></nobr>");
write("</p>");
write("<p id=\"p2_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>275<br></b></nobr>");
write("</p>");
write("<p id=\"p2_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:210px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>150<br></b></nobr>");
write("</p>");
write("<p id=\"p2_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>83<br></b></nobr>");
write("</p>");
write("<p id=\"p2_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>78<br></b></nobr>");
write("</p>");
write("<p id=\"p2_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>234<br></b></nobr>");
write("</p>");
write("<p id=\"p2_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:117px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>230<br></b></nobr>");
write("</p>");
write("<p id=\"p2_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>311<br></b></nobr>");
write("</p>");
write("<p id=\"p2_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>310<br></b></nobr>");
write("</p>");
write("<p id=\"p2_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>303<br></b></nobr>");
write("</p>");
write("<p id=\"p2_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>302<br></b></nobr>");
write("</p>");
write("<p id=\"p2_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>301<br></b></nobr>");
write("</p>");
write("<p id=\"p2_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>300<br></b></nobr>");
write("</p>");
write("<p id=\"p2_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>299<br></b></nobr>");
write("</p>");
write("<p id=\"p2_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:405px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>298<br></b></nobr>");
write("</p>");
write("<p id=\"p2_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-112px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 32 (7.5 A) <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 31 (7.5 A) <br>FUSE <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:425px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACTIVE NOISE <br>CONTROL UNIT <br>(32−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:425px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECPS CONTROL UNIT <br>(25−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER CUT RELAY 1 <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN RELAY 1 <br>(FI MAIN) (2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:402px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ROCKER <br>ARM OIL <br>CONTROL <br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-206px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 20 (15 A) <br>FUSE  <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-301px;top:184px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 19 (20 A) <br>FUSE  <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OIL <br>PRESSURE  <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:439px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION COIL <br>(9−A, B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:91px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 31 (7.5 A) <br>FUSE <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:191px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER CUT RELAY 2 <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-112px;top:91px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 32 (7.5 A) <br>FUSE <br>(8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-206px;top:91px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 20 (15 A) <br>FUSE  <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-301px;top:90px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 19 (20 A) <br>FUSE  <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-430px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN RELAY 2 <br>(FUEL PUMP) (2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:79px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER CUT RELAY 1 <br>(7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER CUT RELAY 2 <br>(7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-430px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN RELAY 2 <br>(FUEL PUMP) (6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:92px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI MAIN RELAY 1 <br>(FI MAIN) (6−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}