with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SJA9EEAJ54260400000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:378px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:95px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:792px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:749px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left headlight (Low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:578px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:535px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:449px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:213px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:128px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:129px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:872px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:921px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:178px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:178px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Horn (High)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:378px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:213px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Horn (Low)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:30px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:362px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 4 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:519px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 1 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 6 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:734px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 3 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:777px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 5 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:450px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:578px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (Low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:792px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:793px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 21 (10 A) <br>FUSE <br>(DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:701px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HEADLIGHT <br>RELAY CIRCUIT <br>(HIGH)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:486px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HEADLIGHT <br>RELAY CIRCUIT <br>(LOW)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:329px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:141px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HORN RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:961px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CONTROL <br>BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:391px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Daytime running lights relay <br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:444px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX <br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}