with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EERJ32320100000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:104px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:47px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:129px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:87px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:133px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:157px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:273px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:390px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:390px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:72px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 22 (BAT) (120 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:72px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:273px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:390px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:129px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 21 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:72px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:337px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:390px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:390px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:337px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:654px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:723px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:390px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:337px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:966px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:883px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:883px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:762px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:762px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:744px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:762px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:819px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ILLUMI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:819px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ILLUMI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:654px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:654px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:723px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:723px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:723px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:1044px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:654px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:176px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>X34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:176px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>X35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:76px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>D6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:133px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:76px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:133px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:144px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:133px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:133px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:286px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>[LT GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:35px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:235px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>AUDIO <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:221px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DASH <br>LIGHTS <br>(BULB)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:221px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DASH <br>LIGHTS <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:847px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:819px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:992px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DASHLIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:546px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>POWER SUPPLY CIRCUIT/CONTROLLER <br>AREA NETWORK CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599px;top:478px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>MULTI−INFORMATION <br>DISPLAY (MID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599px;top:660px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>No. 7 (7.5 A) FUSE <br>(PASSENGER'S UNDER−DASH <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:106px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}