with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EEAJ54260400000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:222px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:53px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:675px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:736px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:551px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:600px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:600px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:296px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:529px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:501px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:472px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:808px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:1009px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:393px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:151px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:179px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:180px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:501px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:473px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:636px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:701px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:701px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PCM (ELD)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:736px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:737px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:808px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:844px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:809px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:844px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:879px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:916px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:915px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:1008px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>c<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:532px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:68px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Internal connection)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:637px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:321px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 13 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:457px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 16 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:485px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 17 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:514px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 18 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:721px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:792px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 23 (P/W) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:828px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 8 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:864px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 10 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:899px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:582px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:605px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(120 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:594px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(BAT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:594px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(AS F/B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:605px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(70 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:582px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:429px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Adaptive cruise control (ACC) unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:529px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:772px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>STARTER CUT RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:971px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 20 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:935px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:986px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:987px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:951px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:952px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:773px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:880px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:64px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 34 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:151px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:151px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Starter motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:108px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BATTERY TERMINAL FUSE BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:108px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Radiator fan control (RFC) relay<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:92px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 35 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:32px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>* : With ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:179px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:251px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:393px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:393px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:251px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:300px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:415px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Adaptive cruise control (ACC) unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:415px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:351px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:393px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:343px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:329px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>High mount brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:358px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:301px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857px;top:189px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:174px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:461px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX <br>(+B HAZARD)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:625px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH <br>FUSE/RELAY BOX <br>(+B AS MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:725px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX <br>(+B IG1 MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:803px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX (+B P/W MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:838px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX (+B IGP MAIN) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:904px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX <br>(+B BACK UP/ACC MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:874px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH <br>FUSE/RELAY BOX (+B H/L WASHER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:981px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX (+B OP2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:946px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX (+B OP1) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:427px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HORN RELAY <br>CIRCUIT <br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:1039px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:473px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 18 (15 A)<br>FUSE <br>(DRIVER'S <br>UNDER−DASH <br>FUSE/RELAY <br>BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:123px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Radiator fan control (RFC) relay <br>(Via radiator fan control (RFC) unit relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:210px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 29 (10 A) FUSE <br>(DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:330px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>ADAPTIVE <br>CRUISE <br>CONTROL <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:221px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}