with(document) {
write("<v:group id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/SJA9EEAA20300000000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:81px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:122px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PSP SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:166px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G203<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:77px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:475px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:645px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:665px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VCC4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:80px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:97px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PSPSW<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:226px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E22<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:245px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SLS<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:465px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:484px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VSSOUT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:309px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AW<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:227px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:274px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SHIFT LOCK <br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:159px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:226px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:247px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:254px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:235px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:88px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:87px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:475px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:353px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:430px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:430px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:430px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:547px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:623px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:623px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:475px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:499px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:656px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:590px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AP<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:785px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:805px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:823px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:832px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:793px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:811px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:811px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:831px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:792px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:47px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>13P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:225px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:256px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:803px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:822px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>OILLVL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:860px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:839px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>33P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:783px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:803px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:786px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:805px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:825px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:854px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:879px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:905px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:930px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:938px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:1009px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:840px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:812px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:793px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:499px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To ECPS CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:852px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>ENGINE OIL<br>LEVEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:963px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AUXILIARY<br>UNDER-DASH<br>FUSE HOLDER<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:902px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>No. 33 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:742px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}