with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:353px;\" coordsize=\"475,353\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:353px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EERA14673217531KDAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:353px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:54px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>: Lubricate with new engine oil<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:35px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>: Clean<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:17px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>: Remove any oil<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:124px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:142px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:308px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:144px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:84px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:124px;font-weight:normal;font-size:9.22pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}