with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:972px;\" coordsize=\"950,972\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:972px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/SJA9EFJJ54230100000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:972px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:939px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:941px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:662px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:804px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G803<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:804px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G802<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:756px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:720px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:899px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:927px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:925px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:942px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:939px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:941px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear headrest subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:804px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G801<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:684px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:684px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:918px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear shelf wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:899px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:899px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:898px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:918px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:920px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:269px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:177px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:63px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:156px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:199px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:134px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:113px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:63px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:41px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:898px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:898px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:804px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:919px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:918px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:941px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:898px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Dashborad wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:896px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:898px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:941px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Roof wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:939px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:941px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p9_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:269px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:662px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:683px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:683px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:719px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:755px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:112px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:134px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:155px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:176px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:198px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:63px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:41px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:62px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:112px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:134px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:155px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p9_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:176px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:233px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:198px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door outer handle light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:369px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:369px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:526px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:526px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:526px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:526px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:555px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:555px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:555px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:555px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:526px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:398px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:398px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:398px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:398px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:419px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:505px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (LS1+)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:526px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (LS1−)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:448px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:448px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:469px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:469px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:269px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:269px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:269px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Alarm control siren<br></b></nobr>");
write("</p>");
write("<p id=\"p9_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Inclination sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p9_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p9_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:319px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:612px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Display unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:591px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:612px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:612px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:612px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:612px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:591px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:591px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:591px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:591px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:633px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:633px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:633px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Fuel fill door opener solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p9_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:876px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p9_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:826px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:826px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:826px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Noise condenser<br></b></nobr>");
write("</p>");
write("<p id=\"p9_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:683px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:683px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:662px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p9_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:676px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right rear seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p9_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:663px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p9_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:662px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p9_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:41px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>To G601<br></b></nobr>");
write("</p>");
write("<p id=\"p9_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:897px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Right rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:926px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Center rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:897px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Left rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:234px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Power rear window sunshade <br>control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:139px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p9_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:452px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p9_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:320px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>Ultrasonic sensor <br>(Buit into the roof console)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}