with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\" coordsize=\"950,995\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:995px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/SJA9EFKJ54230100000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:938px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:960px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:681px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:823px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G803<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:823px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G802<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:775px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:739px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:918px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:946px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:944px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:961px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:960px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear headrest subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575px;top:823px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G801<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:704px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:703px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:281px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:938px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:937px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:938px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear shelf wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:918px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:918px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:917px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:938px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:937px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:939px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:225px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:111px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:203px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:246px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:182px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:161px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:111px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:89px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:917px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:917px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:823px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:938px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:937px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:960px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:917px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Dashborad wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:916px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:917px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:960px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Roof wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:958px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:960px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p9_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:281px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:681px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:703px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:703px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:738px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:774px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:110px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:160px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:181px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:224px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:245px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:110px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:110px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:111px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:89px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:110px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:160px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:181px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:202px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p9_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:224px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door switch<br></b></nobr>");
write("</p>");
write("<p id=\"p9_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:281px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:281px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:245px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear door outer handle light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:388px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:388px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:574px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:574px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:574px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p9_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:574px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:438px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:417px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (first)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:417px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:438px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:438px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:417px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:417px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:438px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left side impact sensor (second)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:524px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (LS1+)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:545px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>SRS unit (LS1−)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:488px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:488px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:605px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:345px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:345px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:345px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk inside beeper<br></b></nobr>");
write("</p>");
write("<p id=\"p9_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Display panel control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p9_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:631px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:610px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:653px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:653px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:653px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Fuel fill door opener solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p9_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:667px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk control unit*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:895px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p9_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:846px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:846px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:846px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Noise condenser<br></b></nobr>");
write("</p>");
write("<p id=\"p9_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:317px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:331px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Power trunk control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:345px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:345px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:703px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:703px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p9_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:291px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:31px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With power trunk<br></b></nobr>");
write("</p>");
write("<p id=\"p9_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Without power trunk<br></b></nobr>");
write("</p>");
write("<p id=\"p9_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:42px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:681px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left rear seat heater*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:695px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right rear seat heater*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:682px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p9_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:681px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p9_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:88px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>To G601<br></b></nobr>");
write("</p>");
write("<p id=\"p9_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:54px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:54px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p9_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:54px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>With rear seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p9_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:917px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Right rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:945px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Center rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:917px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Left rear headrest <br>actuator subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p9_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:282px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Power rear window sunshade <br>control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:188px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p9_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:471px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}