with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:943px;\" coordsize=\"950,943\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:943px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFKJ46643441951FCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:943px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:376px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR Q (14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:206px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR K (12P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:579px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR P (30P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR F (14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:167px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:719px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GRN*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR E (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:45px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:385px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:466px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:167px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:351px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:532px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LT BLU*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:718px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GRN*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:581px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRN*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:37px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:351px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>YEL*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875px;top:580px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRN*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:395px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLU*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RED*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>LT BLU*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:533px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>RED*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:759px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR G (6P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:894px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40px;top:853px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>*1: LHD model<br>*2: RHD model<br>*3: 1 motion unlock type<br>*4: 2 motions unlock type<br>*5: Connector view shown rotated 180 ° from actual position in the under-dash fuse/relay box.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:180px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>CONNECTOR N (45P)*<sup>5</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:228px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>YEL*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:400px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BLU*<sup>1</sup><br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}