with(document) {
write("<v:group id=\"group14\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:633px;\" coordsize=\"950,633\">");
write("<v:rect id=\"rect14\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:633px;\">");
write("<img id=\"img14\" name=\"PrtImgId\" src=\"../img/SJA9EFKJ54230100000EAAD14.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:633px;border-color:#ffffff\">");
write("<p id=\"p14_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:573px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p14_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:572px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p14_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:574px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:251px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p14_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:59px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:59px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:81px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:102px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:102px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:145px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:123px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:123px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:145px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Headlight washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p14_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:166px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Washer fluid level switch<br></b></nobr>");
write("</p>");
write("<p id=\"p14_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:166px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:352px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:352px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Radiator fan control (RFC) unit <br></b></nobr>");
write("</p>");
write("<p id=\"p14_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:266px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:330px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:309px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:537px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p14_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:448px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:459px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Relay control module<br></b></nobr>");
write("</p>");
write("<p id=\"p14_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:502px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Windshield wiper intermittent relay circuit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:481px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Windshield washer motor relay circuit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:459px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:38px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:59px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:81px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:102px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:123px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:145px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:166px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:266px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:309px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:330px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:352px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:459px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:81px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right HID unit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:188px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:188px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:188px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:188px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p14_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:593px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p14_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:595px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>A/C compressor clutch subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p14_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:595px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p14_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:574px;top:244px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G351<br></b></nobr>");
write("</p>");
write("<p id=\"p14_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:309px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left HID unit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:330px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:288px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:266px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:373px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:373px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:373px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Radiator fan control (RFC) unit <br></b></nobr>");
write("</p>");
write("<p id=\"p14_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:469px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(In the relay control module)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:491px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(In the relay control module)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p14_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:395px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:415px;font-weight:normal;font-size:6.75pt;\">");
write("<nobr><b>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}