with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EERA20326428001MAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:279px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BASE GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:376px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>To FUEL RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:508px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>To<br>EVAPORATIVE<br>EMISSION (EVAP)<br>CANISTER PURGE<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:642px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Make sure the<br>clamp is in<br>position as shown.<br></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:134px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:22px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:48px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:151px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:4px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:286px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BASE GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:597px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:598px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:819px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Make sure the<br>clamp is in<br>position as shown.<br></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:877px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:876px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>D:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:816px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>E:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:717px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>115 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:891px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:1020px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MARK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:1041px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>in position as shown.<br></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:912px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:786px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>115 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:735px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TOP SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:714px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>in position as shown.<br></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:769px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:832px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>120 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:889px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TOP SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:848px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>in position as shown.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}