with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFJ000000000000EBA218.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:242px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:242px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:484px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S DOOR MULTIPLEX CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:773px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:812px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S POWER MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-116px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:812px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10 [5]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8 [7]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:569px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:4px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-4px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UN−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-4px;top:645px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:812px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:391px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>(0.84 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:384px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:721px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:407px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:364px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UN−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:371px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:371px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:773px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:812px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-125px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COURTESY−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:427px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VBU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[LT GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:497px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:490px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RSEH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:504px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RSEV<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:615px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:712px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UART<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:340px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:356px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:451px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:464px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B P/W<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:285px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>142<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:285px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>259<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:383px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>393<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:383px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>137<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (10 A) <br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (10 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:682px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TILT <br>(VERTICAL)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:682px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SWING <br>(HORIZONTAL)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:713px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S <br>POWER MIRROR <br>POSITION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:685px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER <br>MIRROR <br>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-244px;top:340px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>POCKET <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-207px;top:555px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOOR <br>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-31px;top:555px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOOR <br>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:646px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR LOCK <br>KNOB <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-244px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DOOR <br>SWITCH <br>(Closed : <br>Door open)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:324px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>DOOR LOCK SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-412px;top:632px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>OUTER <br>HANDLE <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-274px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR <br>WINDOW SWITCH <br>(17−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:348px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S DOOR <br>MULTIPLEX <br>CONTROL UNIT <br>(17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:356px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 3 (30 A) <br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-372px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR <br>WINDOW SWITCH <br>(17−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}