with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SJA9EF5J54260400000EAAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:377px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:95px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:792px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:835px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:792px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:577px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left headlight (Low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:620px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:577px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:442px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:213px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:127px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:128px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:914px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:963px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:177px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:177px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Horn (High)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:377px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:213px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Horn (Low)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:30px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:362px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 4 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:562px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 1 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:605px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 6 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:776px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 3 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:819px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>No. 5 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:443px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:620px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (Low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:835px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right headlight (High beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:407px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:470px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:872px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>PASSENGER'S <br>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:743px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HEADLIGHT <br>RELAY CIRCUIT <br>(HIGH)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:529px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HEADLIGHT <br>RELAY CIRCUIT <br>(LOW)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:328px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:141px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>HORN RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:1004px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>CONTROL <br>BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:437px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH <br>FUSE/RELAY BOX <br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722px;top:395px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH <br>FUSE/RELAY BOX <br>(OUTER ILL+)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}