with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFJ000000000000EBA922.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G851<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G604<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:325px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CLOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SUNROOF CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HALL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:325px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OPEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:315px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OPEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CLOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:353px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:345px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TILT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:326px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SUNROOF SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UART<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276px;top:438px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:398px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:380px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:372px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:273px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>284<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>129<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>229<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>69<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>375<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>393<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>396<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>392<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>395<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:418px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>393<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>276<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>121<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>280<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>124<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>355<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:287px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>254<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER RELAY <br>(3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:366px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR <br>WINDOW <br>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:368px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>NOISE <br>CONDENSER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER RELAY <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:424px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S <br>MPCS UNIT <br>(17−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 28 (20 A) <br>FUSE <br>(3−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 28 (20 A) <br>FUSE <br>(7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:343px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ROOF <br>CONSOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:424px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS CONTROLLER <br>(In the gauge control module)<br>(13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 6 (7.5 A) <br>FUSE <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:426px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ROOF CONSOLE <br>(22−C, D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:275px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SUNROOF CONTROL UNIT <br>(22−B, C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:426px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTOMATIC DIMMING <br>POWER MIRROR <br>(16−C) (18−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:351px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTOMATIC DIMMING <br>INSIDE MIRROR <br>(Has built−in control unit)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 21 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 21 (10 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:278px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Combination Switch Control Unit, Rear Window Defogger, Automatic Dimming Inside Mirror, Sunroof<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>COMBINATION LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>COMBINATION SWITCH CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:236px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:216px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DIMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:120px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:197px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:58px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:58px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:120px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:173px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DIMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:166px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:178px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:186px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MIST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>COMBINATION SWITCH CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>COMBINATION LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:58px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:58px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:90px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:176px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:142px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:197px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:210px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:236px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599px;top:216px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:51px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:51px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>65<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>203<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>226<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>259<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:72px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>205<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>204<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>437<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:76px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>437<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:168px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERMITTENT <br>WIPER DWELL <br>TIME <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:169px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:171px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:178px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT/ <br>REAR <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:184px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TURN SIGNAL <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 21 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (10 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:42px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAY CONTROL MODULE <br>(Buit into the <br>under−hood fuse/relay box) <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:156px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:178px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT/ <br>REAR <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:171px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:169px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:160px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>INTERMITTENT <br>WIPER DWELL <br>TIME <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:184px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TURN SIGNAL <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 21 (10 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:59px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (10 A) <br>FUSE <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAY CONTROL MODULE <br>(Buit into the <br>under−hood fuse/relay box) <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:55px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAY CONTROL MODULE <br>(Buit into the <br>under−hood fuse/relay box) <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:42px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAY CONTROL MODULE <br>(Buit into the <br>under−hood fuse/relay box) <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:49px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:49px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(14−D)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}