with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA923.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Cable Reel<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:37px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:37px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:41px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:37px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:308px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CRUISE CONTROL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:308px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SET/RESUME/CANCEL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CANCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RESUME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:214px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:308px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HORN SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>0.01µF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:288px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3.9 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:293px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:288px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:268px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>100 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>270 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>470 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1.2 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>10 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:336px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:336px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779px;top:205px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:283px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:136px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:253px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669px;top:128px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:136px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:128px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:336px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:320px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>S−DN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:286px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:289px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>S−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:234px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:167px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:175px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:303px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:218px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>197<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>344<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>345<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>343<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>315<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>316<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:219px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>289<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>146<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>382<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>383<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>338<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:126px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAY CONTROL <br>MODULE <br>(Built into the <br>under−hood <br>fuse/relay box) <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:138px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE <br>(13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:137px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE <br>(13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:203px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH <br>(23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:201px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PADDLE <br>SHIFTER <br>(23−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:201px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SET/RESUME/<br>CANCEL  SWITCH <br>(23−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:137px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:138px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUDIO UNIT <br>(32−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PADDLE <br>SHIFTER <br>(23−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SET/RESUME/<br>CANCEL  SWITCH <br>(23−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:342px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CABLE <br>REEL <br>(23−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:132px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS CONTROLLER <br>(In the gauge control module) <br>(13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:186px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:137px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:224px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH <br>(23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:138px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PCM <br>(11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:262px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PADDLE SHIFTER − <br>(DOWNSHIFT SWITCH)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468px;top:262px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PADDLE SHIFTER + <br>(UPSHIFT SWITCH)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:344px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH <br>(23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:126px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RELAY CONTROL <br>MODULE <br>(Built into the <br>under−hood <br>fuse/relay box) <br>(5−D)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}