with(document) {
write("<v:group id=\"group11\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect11\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img11\" name=\"PrtImgId\" src=\"../img/SJA9EFAA20300000000EAAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p11_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:319px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To IMMOBILIZER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:104px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:114px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:121px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:133px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:150px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:168px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:175px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:186px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:193px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:112px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E16<br></b></nobr>");
write("</p>");
write("<p id=\"p11_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:333px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E24<br></b></nobr>");
write("</p>");
write("<p id=\"p11_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:258px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p11_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:298px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p11_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:180px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:581px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:506px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Brake pedal pressed: closed<br>Brake pedal released: open<br></b></nobr>");
write("</p>");
write("<p id=\"p11_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:601px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BF<br></b></nobr>");
write("</p>");
write("<p id=\"p11_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:657px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P JUNCTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:498px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:514px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p11_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:554px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:570px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p11_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:130px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:351px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WEN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:498px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:507px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:515px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:525px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:536px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:554px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:547px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>Brake pedal pressed: open<br>Brake pedal released: closed<br></b></nobr>");
write("</p>");
write("<p id=\"p11_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:599px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:599px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:599px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:636px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BE<br></b></nobr>");
write("</p>");
write("<p id=\"p11_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:416px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:546px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:563px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:103px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:31px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:122px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:342px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:506px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:747px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D17<br></b></nobr>");
write("</p>");
write("<p id=\"p11_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:763px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SUPP<br></b></nobr>");
write("</p>");
write("<p id=\"p11_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:832px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D15<br></b></nobr>");
write("</p>");
write("<p id=\"p11_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:848px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SDNP<br></b></nobr>");
write("</p>");
write("<p id=\"p11_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:755px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:840px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:597px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:470px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:103px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:103px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:32px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:209px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:201px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:367px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:391px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:747px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:753px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>STEERING<br>WHEEL<br>UPSHIFT (+)<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:841px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>STEERING<br>WHEEL<br>DOWNSHIFT (−)<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:790px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:832px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:875px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:1002px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:955px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p11_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:963px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:745px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p11_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:830px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p11_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:956px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p11_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:965px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:1025px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p11_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:830px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:745px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:841px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:755px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:799px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:882px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:344px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:415px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To SH-AWD CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:438px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To ACC CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:461px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>To POP-UP HOOD UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:157px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:140px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:344px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:367px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:390px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:417px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:439px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:463px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:138px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:226px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:246px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:206px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p11_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:206px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p11_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:562px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:546px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BA<br></b></nobr>");
write("</p>");
write("<p id=\"p11_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:546px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BB<br></b></nobr>");
write("</p>");
write("<p id=\"p11_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:417px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:486px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:486px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:218px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:225px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678px;top:235px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p11_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:243px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541px;top:298px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BC<br></b></nobr>");
write("</p>");
write("<p id=\"p11_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:298px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BD<br></b></nobr>");
write("</p>");
write("<p id=\"p11_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:252px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:259px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}