with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA924.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>VSA System, Adaptive Front Lighting System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:257px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545px;top:265px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Except KD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:64px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:64px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:60px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:60px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196px;top:249px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G202<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:121px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:111px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHEEL SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:337px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:189px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:189px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:165px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:189px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:211px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[LT BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:198px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YAW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GLAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GLONG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RR−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RL−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FR−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MR−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FL−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAN LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAN HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FSR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:179px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:279px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:252px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:221px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:314px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:292px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:305px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:304px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[ORN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:322px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:300px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:238px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>ADAPTIVE FRONT LIGHTING CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G203<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GND2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GND1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:298px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:360px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565px;top:360px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:350px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:232px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WIPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:232px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>OP1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:244px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:360px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:257px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:265px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SSF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SSR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>SV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:144px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:158px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[BRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:154px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEPPING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MLA1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MLA2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MLB1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MLB2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:871px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:871px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:889px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:878px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MRB2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MRB1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MRA2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MRA1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HSV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LHSS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HSG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822px;top:307px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:255px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:248px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHSS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:267px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HALL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HALL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>STEPPING MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:209px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AV<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:222px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:170px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:213px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[BRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>332<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>334<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>333<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>59<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>60<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>334<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>333<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAN LO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:228px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>CAN HI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:112px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:112px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:112px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:112px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>157<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>158<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>212<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>213<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:104px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:104px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:104px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:104px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:150px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>211<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:608px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>286<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>71<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:172px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:211px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[RED]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499px;top:104px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>195<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:316px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>327<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:278px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>146<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:278px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>289<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:374px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>339<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:54px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_331\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:54px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_332\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:54px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_333\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_334\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:349px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YAW RATE−LATERAL <br>ACCELERATION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_335\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(11−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_336\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE  <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_337\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:157px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE  <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_338\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 18 (15 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_339\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 17 (30 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_340\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 18 (40 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_341\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 18 (15 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_342\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:326px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_343\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AFS <br>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_344\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:336px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LIGHT <br>(LEDx3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_345\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(13−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_346\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:266px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_347\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 29 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_348\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_349\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 29 (10 A) <br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_350\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 11 (15 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_351\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:159px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 11 (15 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_352\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:119px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR <br>LEVELING SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_353\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:119px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT <br>LEVELING SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_354\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:361px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT ADAPTIVE FRONT LIGHTING GEARBOX <br>(Horizontal movement)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_355\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:361px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT ADAPTIVE FRONT LIGHTING GEARBOX <br>(Horizontal movement)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_356\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:103px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT HEADLIGHT <br>LEVELING MOTOR <br>(Vertical movement)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_357\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:103px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT HEADLIGHT <br>LEVELING MOTOR <br>(Vertical movement)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_358\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:143px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVING <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_359\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:143px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVING <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_360\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 18 (15 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_361\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 17 (30 A) <br>FUSE <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_362\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 18 (40 A) <br>FUSE <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_363\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 18 (15 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_364\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:113px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}