with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA919.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:23px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G653<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:385px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:385px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:332px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:348px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:321px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:385px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:385px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:250px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743px;top:358px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:370px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:394px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:358px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:370px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:381px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:384px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>(0.56 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:306px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:333px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:333px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:333px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:347px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:333px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:402px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:362px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[ORN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:291px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:431px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[G506]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:431px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[G601]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:319px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797px;top:427px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:387px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:370px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:346px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:338px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845px;top:392px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:392px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867px;top:378px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:392px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>122<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>288<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>187<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>361<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>362<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>363<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>364<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>365<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>366<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>271<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>289<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:341px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>125<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:341px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>146<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>341<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>342<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>338<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:414px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>352<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>349<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>350<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867px;top:356px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>351<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>270<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>184<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>143<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:274px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>145<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:313px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>347<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:294px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>348<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:309px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861px;top:313px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:873px;top:264px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 16 (15 A) <br>FUSE <br>(3−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LICENSE <br>PLATE <br>LIGHTS <br>(5 Wx2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:334px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRAKE <br>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRAKE <br>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>TAILLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>TAILLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:374px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TAILLIGHT <br>(LEDx18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:374px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TAILLIGHT <br>(LEDx18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>POSITION <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:335px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LICENSE <br>PLATE <br>LIGHTS <br>(5 Wx2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRAKE <br>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:328px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BRAKE <br>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>TAILLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:318px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>TAILLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:374px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TAILLIGHT <br>(LEDx18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:374px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TAILLIGHT <br>(LEDx18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:379px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HAZARD<br>WARNING<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:423px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT<br>REAR<br>TURN<br>SIGNAL<br>LIGHT<br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT SIDE <br>TURN SIGNAL<br>LIGHT (LED) <br>(Built into <br>the mirror)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>FRONT<br>TURN<br>SIGNAL<br>LIGHT<br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br>FRONT<br>TURN<br>SIGNAL<br>LIGHT<br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:383px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT SIDE <br>TURN SIGNAL<br>LIGHT (LED) <br>(Built into <br>the mirror)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:352px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br>REAR<br>TURN<br>SIGNAL<br>LIGHT<br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TURN SIGNAL/ <br>HAZARD RELAY 1 (MICU) <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TURN SIGNAL/ <br>HAZARD RELAY 1 (MICU) <br>(14−B, C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:424px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 16 (15 A) <br>FUSE <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:327px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:280px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 7 (7.5 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:354px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TURN SIGNAL/<br>HAZARD RELAY 2 <br>(SOUNDER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:278px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>TURN SIGNAL/ <br>HAZARD RELAY 1 <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:404px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>AUTOMATIC LIGHTING <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:852px;top:344px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:258px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:260px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>SECURITY <br>HAZARD <br>RELAY  <br>(15−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857px;top:272px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>SECURITY <br>HAZARD <br>RELAY  <br>(15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:920px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:19px;font-weight:normal;font-size:8.82pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:12px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>Headlight System, Front Fog Lights, Rear Fog Light, Taillights, Front Position Lights, License Plate Lights, Turn Signal/Hazard Warning Light, Automatic Lighting<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:36px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:53px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:53px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:46px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:50px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Except KD, KF models<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:39px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>PASENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:62px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:148px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:148px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:133px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:133px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:148px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:148px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LOW (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:125px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:155px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:106px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:133px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:133px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:117px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:86px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G653<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:173px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*4, *6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:86px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:207px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:183px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:173px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:33px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_331\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_332\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_333\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>188<br></b></nobr>");
write("</p>");
write("<p id=\"p1_334\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>190<br></b></nobr>");
write("</p>");
write("<p id=\"p1_335\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>189<br></b></nobr>");
write("</p>");
write("<p id=\"p1_336\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>191<br></b></nobr>");
write("</p>");
write("<p id=\"p1_337\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_338\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>175<br></b></nobr>");
write("</p>");
write("<p id=\"p1_339\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>372<br></b></nobr>");
write("</p>");
write("<p id=\"p1_340\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>372<br></b></nobr>");
write("</p>");
write("<p id=\"p1_341\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_342\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_343\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:74px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_344\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:57px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>174<br></b></nobr>");
write("</p>");
write("<p id=\"p1_345\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:53px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>Except KD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_346\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT<br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_347\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_348\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH <br>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_349\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH <br>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_350\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>FOG <br>LIGHT <br>(55 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_351\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>FOG <br>LIGHT <br>(55 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_352\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT<br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_353\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:102px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT<br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_354\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH <br>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_355\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:124px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>HIGH <br>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_356\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>FOG <br>LIGHT <br>(55 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_357\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:123px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>FOG <br>LIGHT <br>(55 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_358\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:82px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR FOG <br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_359\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 1 (15 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_360\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 3 (10 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_361\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT FOG LIGHT RELAY <br>(1−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_362\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 6 (15 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_363\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 5 (10 A) <br>FUSE <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_364\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 1 (15 A) <br>FUSE <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_365\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 3 (10 A) <br>FUSE <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_366\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 6 (15 A) <br>FUSE <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_367\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:43px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>No. 5 (10 A) <br>FUSE <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_368\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:45px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>FRONT FOG LIGHT RELAY <br>(5−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_369\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:47px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_370\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:82px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>REAR FOG <br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_371\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:47px;font-weight:normal;font-size:3.00pt;\">");
write("<nobr><b>MICU <br>(15−A)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}