with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:895px;\" coordsize=\"950,895\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:895px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EEAH10800000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:895px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:164px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7px;top:263px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:803px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE CRUISE CONTROL (ACC) UNIT<br><a href=\"javascript:CtsProc('0','000000000001095','i000')\"></b>Removal/Installation,</a><br>  in the Shop Manual, P/N 62SJA00B<br><a href=\"javascript:CtsProc('0','000000000001139','i000')\">CMBS Initial Check,</a><br>  in the Shop Manual, P/N 62SJA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:53px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:519px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684px;top:631px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:21px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:711px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>BRAKE FLUID PRESSURE SENSOR<br><a href=\"javascript:CtsProc('0','000000000001096','i000')\"></b>Replacement,</a><br>  in the Shop Manual, P/N 62SJA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:739px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE CRUISE CONTROL <br>(ACC) RELAY<br><a href=\"javascript:CtsProc('0','000000000003438','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:4px;top:654px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MILLIMETER WAVE RADAR<br><a href=\"javascript:CtsProc('0','000000000002455','i000')\"></b>Removal/Installation,</a><br><a href=\"javascript:CtsProc('0','000000000002456','i000')\">Aiming,</a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}