with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/SJA9EFAA20300000000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:252px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AQ<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:166px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:156px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:145px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:134px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:186px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:175px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:207px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:196px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:118px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:106px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:88px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:74px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:137px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:156px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SG3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:76px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:96px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VCC3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:109px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:123px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>APSA<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:178px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:192px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>APSB<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:237px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>APP SENSOR A/B<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:793px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>THROTTLE<br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:685px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:756px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:776px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:664px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:672px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:734px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:827px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>THROTTLE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804px;top:603px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br>CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:454px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:511px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:406px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:339px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A25<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:353px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SEFD<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:367px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A26<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:381px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>SEDF<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:543px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:564px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:523px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:532px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:553px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:573px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:532px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:552px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:573px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:543px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:564px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:523px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:462px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:441px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:421px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:400px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:468px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:448px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:407px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:427px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:468px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:448px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:461px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:440px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:420px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:399px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:311px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:317px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:317px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:310px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:367px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:338px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:345px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:373px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:345px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:373px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:366px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560px;top:337px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:571px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:708px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:693px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:725px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:714px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:653px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:888px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:959px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:979px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:867px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:967px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:987px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800px;top:911px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:896px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:917px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:1017px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IMT<br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:73px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:105px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:177px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:135px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:144px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:185px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:116px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:86px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:829px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p8_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:875px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:829px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p8_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:889px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:904px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IMTM<br></b></nobr>");
write("</p>");
write("<p id=\"p8_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:959px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:973px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IMT+<br></b></nobr>");
write("</p>");
write("<p id=\"p8_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:999px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:1014px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>IMT−<br></b></nobr>");
write("</p>");
write("<p id=\"p8_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:967px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:1008px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:896px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:157px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:58px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>20P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:897px;top:117px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p8_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894px;top:185px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p8_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:698px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p8_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905px;top:698px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p8_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:290px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>13P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:389px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>17P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:427px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:406px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:511px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p8_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:784px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:764px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:267px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:259px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:273px;font-weight:normal;font-size:6.50pt;\">");
write("<nobr><b>VCC4<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}