with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EEAJ54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:687px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1<br>(FI MAIN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:663px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>TURN SIGNAL/HAZARD RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:697px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ACCESSORY POWER SOCKET RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:756px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MICU<br>(Built into the driver's <br>under-dash fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:978px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:1033px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>STARTER CUT RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:1057px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>A/F SENSOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:1009px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br>(FUEL PUMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:769px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>IGNITION COIL RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:69px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>KEYLESS CONVERTER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:17px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE FRONT LIGHTING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:65px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ELECTRONICALLY CONTROLLED<br>POWER STEERING (ECPS) CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:331px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>ADAPTIVE CRUISE<br>CONTROL (ACC) UNIT<br>(With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:607px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUXILIARY UNDER-DASH<br>FUSE HOLDER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}