with(document) {
write("<v:group id=\"group12\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:520px;\" coordsize=\"950,520\">");
write("<v:rect id=\"rect12\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:520px;\">");
write("<img id=\"img12\" name=\"PrtImgId\" src=\"../img/SJA9EFJJ54230100000EAAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:520px;border-color:#ffffff\">");
write("<p id=\"p12_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:473px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:475px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:267px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:39px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:39px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:473px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear window defogger ground wire<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:424px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>G851<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:324px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear window defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:324px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:474px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:39px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:96px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:324px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk lid latch switch<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:167px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Trunk lid opener solenoid<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}