with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA115.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:23px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>MICU, Trunk Lid Opener, Fuel Fill Door Opener, Keyless/Power Door Locks/Security System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PNK]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:537px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PUR]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P13 [P2]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PUR]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEY SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEY SOL−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P−PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Q10 [Q11]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P16 [P29]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ATP P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P21 [P24]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>E14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>P17 [P28]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>N26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BK SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FOG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:500px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:493px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:493px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:493px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:627px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>369<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>142<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>370<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>371<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>317<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>372<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>329<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>322<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>328<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>331<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:573px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:581px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[PUR]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>RELAY <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:637px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRAKE <br>PEDAL <br>POSITION <br>SWITCH <br>(21−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SRS UNIT <br>(34−B) <br>(35−B) <br>(36−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TRANSMISSION <br>RANGE SWITCH <br>(P position) <br>(11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR FOG <br>LIGHT <br>(19−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>SWITCH <br>(21−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PARK PIN <br>SWITCH <br>(9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEY SWITCH <br>(Ignition <br>key switch) <br>(9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IMOES <br>UNIT <br>(11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:638px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>KEY <br>INTERLOCK <br>SOLENOID <br>(9−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}