with(document) {
write("<v:group id=\"group10\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:814px;\" coordsize=\"950,814\">");
write("<v:rect id=\"rect10\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:814px;\">");
write("<img id=\"img10\" name=\"PrtImgId\" src=\"../img/SJA9EE8J54260400000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:814px;border-color:#ffffff\">");
write("<p id=\"p10_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:63px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:421px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right security hazard relay<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:407px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left security hazard relay<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:467px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:564px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Noise condenser<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:686px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:686px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PCM (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:550px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Rear window defogger (+)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:550px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:478px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Turn signal/hazard relay 1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:407px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106px;top:128px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:86px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:622px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:664px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:528px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:486px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:343px;font-weight:normal;font-size:5.66pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:386px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:221px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508px;top:278px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:350px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:338px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:278px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>High mount brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:293px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:307px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:150px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>PCM (BKSW)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:31px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 13 (15 A) <br>FUSE <br>(UNDER−HOOD <br>FUSE/REAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:175px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION SWITCH <br>(Closed: Pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:288px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>No. 16 (15 A) <br>FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:444px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:580px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>A/C <br>COMPRESSOR <br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:435px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Turn signal/hazard relay 2 <br>(Via hazard warning switch)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}