with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EGKJ36200000000CAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:232px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:347px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>Destination<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:347px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DVD−ROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:253px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>YAW RATE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:153px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GPS tuning<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201px;top:124px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GPS RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:94px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:124px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>GPS ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:95px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:37px;font-weight:normal;font-size:6.82pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:149px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>VOICE <br>PROMPTS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:60px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Audio <br>guidance<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:240px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Guide <br>processing<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:283px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Map scroll <br>Change of reduced <br>scale of map<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:275px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Correction of <br>map matching<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:276px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Detection of <br>direction change<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:147px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Detection of <br>vehicle position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:219px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Detection of <br>travel distance<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:184px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>PCM <br>(VEHICLE SPEED PULSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:218px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Perception of <br>vehicle position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:216px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Data process concerning map <br>and vehicle position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:147px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Reception of radio <br>wave from satellite<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:418px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Interface Dial <br>switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:418px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Reverse <br>signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:331px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Rearview <br>camera <br>proccessing<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:419px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>REARVIEW <br>CAMERA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:26px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>AUDIO−HVAC <br>SUBDISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:417px;font-weight:normal;font-size:6.76pt;\">");
write("<nobr><b>Gauge Control Module <br>(Illumi cancel)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}