with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SJA9EFAJ14235000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:18px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HFT/NAVIGATION MICROPHONE<br>(Built into the roof console)<br><a href=\"javascript:CtsProc('0','000000000003426','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166px;top:613px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>DISPLAY UNIT<br><a href=\"javascript:CtsProc('0','000000000000597','i000')\"></b>Replacement,</a><br> in the Shop Manual,<br> P/N 62SJA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507px;top:767px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE<br>CONTROL UNIT<br><a href=\"javascript:CtsProc('0','000000000003448','iG05')\"></b>Self-diagnostic Function,<br></a><br><a href=\"javascript:CtsProc('0','000000000003425','i000')\">Input Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:703px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>MULTI-INFORMATION<br>DISPLAY (MID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:233px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HFT VOLUME<br>(Using audio unit volume knob)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:679px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>AUDIO UNIT<br><a href=\"javascript:CtsProc('0','000000000003391','i000')\"></b>Connector Inputs and Outputs,<br></a><br><a href=\"javascript:CtsProc('0','000000000000393','i000')\">Replacement,</a><br> in the Shop Manual, P/N 62SJA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:811px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>HFT-VOICE CONTROL SWITCH<br><a href=\"javascript:CtsProc('0','000000000000406','i000')\"></b>Test,</a><br> in the Shop Manual,<br> P/N 62SJA00B<br><a href=\"javascript:CtsProc('0','000000000000406','i000')\">Replacement,</a><br> in the Shop Manual,<br> P/N 62SJA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:857px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>NAVIGATION UNIT (in trunk)<br><a href=\"javascript:CtsProc('0','000000000003761','i000')\"></b>Connector Inputs and Outputs,</a><br><a href=\"javascript:CtsProc('0','000000000001207','i000')\">Removal/Installation,</a><br> in the Shop Manual, P/N 62SJA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:852px;top:292px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:274px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b>SPEAKER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}