with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA232.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-31px;top:493px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:546px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-33px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-84px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-94px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-97px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOAD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-63px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-35px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-68px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLANK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-68px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLANK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-97px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LOAD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-214px;top:710px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO−HVAC SUBDISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-53px;top:672px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-32px;top:586px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-18px;top:586px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:714px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:726px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:726px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:726px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:764px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:764px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:672px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:662px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:697px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERFACE DIAL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:540px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:540px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PRE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SW +B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:526px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUB+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SW +B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:550px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REMOTE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:714px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>JOG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:714px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SHLD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:707px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>JOG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:826px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:826px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G653<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:832px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548px;top:832px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[G602]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:420px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:790px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:790px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:737px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:737px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296px;top:498px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:498px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:498px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:498px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-76px;top:411px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-76px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-5px;top:411px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-5px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:584px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:550px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>REMOTE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SW GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GA−NET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GA−NET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GA−NET<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:688px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS SH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-31px;top:361px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>295<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-31px;top:454px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>152<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:627px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>295<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:627px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>152<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:813px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>394<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:813px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>393<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:667px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>383<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:667px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>382<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>396<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>397<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:559px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT (33−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:559px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT (33−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:566px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:570px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SECURITY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:667px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>395<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-234px;top:353px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBWINDOW <br>ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-234px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBANTENNA <br>MODULE <br>(AMPLIFIER)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-494px;top:686px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(In the gauge <br>control module) <br>(13−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-325px;top:424px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MAIN ANTENNA <br>MODULE <br>(AMPLIFIER)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-399px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL UNIT <br>(31−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:838px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT <br>(33−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-113px;top:428px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-113px;top:335px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 5 (7.5 A) <br>FUSE <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-38px;top:335px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC <br>RELAY <br>(8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-38px;top:428px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC <br>RELAY <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:601px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC <br>RELAY <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:601px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC <br>RELAY <br>(8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:691px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RADIO REMOTE SWITCH <br>(23−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:687px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT <br>(33−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:265px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBWOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:433px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:403px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STEREO AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:307px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:360px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:316px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:487px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562px;top:296px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TWD−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TWD+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TWD−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TWD+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CTR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SUBW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SP+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:278px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:295px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:185px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:202px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:375px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RG−L+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:389px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RG−L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:299px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>391<br></b></nobr>");
write("</p>");
write("<p id=\"p2_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:299px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>390<br></b></nobr>");
write("</p>");
write("<p id=\"p2_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:228px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>277<br></b></nobr>");
write("</p>");
write("<p id=\"p2_331\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:321px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>130<br></b></nobr>");
write("</p>");
write("<p id=\"p2_332\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT <br>CENTER <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_333\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR<br>TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_334\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR <br>TWIDDLER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_335\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR <br>TWIDDLER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_336\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT REAR <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_337\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:258px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT REAR <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_338\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR <br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_339\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR<br>TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_340\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR<br>SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_341\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:295px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (30 A) <br>FUSE <br>(4−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_342\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:202px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 2 (30 A) <br>FUSE <br>(7−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_343\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607px;top:274px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT <br>(33−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}