with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/SJA9EE8A20300000000DBAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:616px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PSP SWITCH<br>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:615px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>13P CONNECTOR<br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:208px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>APP SENSOR<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:68px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ELD (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:206px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>3P CONNECTOR<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:493px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RFC UNIT<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:68px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496px;top:68px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:68px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:207px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>34P CONNECTOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:360px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819px;top:359px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>MAF SENSOR/ <br>IAT SENSOR <br>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:207px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>AUXILIARY UNDER-DASH<br>FUSE/RELAY HOLDER<br>(STARTER CUT RELAY 1)<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:360px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:360px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>DRIVER'S UNDER-DASH<br>FUSE/RELAY BOX<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:359px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>AUXILIARY UNDER-HOOD<br>RELAY BOX<br>(RFC UNIT RELAY)<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:494px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>RFC UNIT<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:493px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>6P CONNECTOR <br>(KD model)<br>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:492px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>ECT SENSOR 2 <br>(KD model)<br>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:492px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT <br>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:615px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>12P JUNCTION <br>CONNECTOR <br>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479px;top:616px;font-weight:normal;font-size:7.41pt;\">");
write("<nobr><b>PASSENGER'S UNDER-DASH <br>FUSE/RELAY BOX <br>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18px;top:737px;font-weight:normal;font-size:8.69pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}