with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SJA9EFJ000000000000EBA332.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-14px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:717px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-94px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-100px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-29px;top:704px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIC SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:704px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIC+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:704px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIC−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-100px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVI<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVI<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:635px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-14px;top:668px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-29px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TELM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-29px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TELM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:689px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:681px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>TELM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:863px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ROOF CONSOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:759px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:759px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:792px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-45px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:653px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-45px;top:653px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:728px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-10px;top:728px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:653px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-10px;top:653px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>413<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>412<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-58px;top:583px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>427<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:617px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-22px;top:591px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>414<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-10px;top:618px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8px;top:842px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT/NAVIGATION <br>MICROPHONE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-213px;top:829px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT <br>(31−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-151px;top:558px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT <br>(32−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:558px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STEREO AMPLIFIER <br>(31−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579px;top:37px;font-weight:normal;font-size:17.63pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:66px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:66px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:73px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:73px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:66px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:80px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:80px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:87px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:87px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:94px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:87px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:73px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:80px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PASSENGER'S UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:158px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:158px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:176px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:101px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:101px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:204px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-141px;top:192px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-19px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-50px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:225px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B19<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:143px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:167px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:180px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:204px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:204px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-20px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-20px;top:204px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:204px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:211px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:204px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>G−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-20px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-20px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:10px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-81px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-50px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-81px;top:436px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-50px;top:436px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-82px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:344px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:351px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BUS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-9px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-40px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B26<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:245px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:294px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:294px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61px;top:82px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-23px;top:65px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-27px;top:82px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-19px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-5px;top:374px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>COMM1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p3_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SIG−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:342px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:318px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BACK−LT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:305px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:267px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CAN HI<br></b></nobr>");
write("</p>");
write("<p id=\"p3_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:349px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CAN LO<br></b></nobr>");
write("</p>");
write("<p id=\"p3_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:362px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p3_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:374px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:414px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:374px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:374px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:413px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:414px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:147px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:147px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p3_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:147px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:232px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>375<br></b></nobr>");
write("</p>");
write("<p id=\"p3_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>151<br></b></nobr>");
write("</p>");
write("<p id=\"p3_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-45px;top:108px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>305<br></b></nobr>");
write("</p>");
write("<p id=\"p3_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:498px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>421<br></b></nobr>");
write("</p>");
write("<p id=\"p3_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>338<br></b></nobr>");
write("</p>");
write("<p id=\"p3_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:467px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>350<br></b></nobr>");
write("</p>");
write("<p id=\"p3_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:467px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>351<br></b></nobr>");
write("</p>");
write("<p id=\"p3_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>423<br></b></nobr>");
write("</p>");
write("<p id=\"p3_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>424<br></b></nobr>");
write("</p>");
write("<p id=\"p3_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:467px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>425<br></b></nobr>");
write("</p>");
write("<p id=\"p3_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:467px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>426<br></b></nobr>");
write("</p>");
write("<p id=\"p3_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>427<br></b></nobr>");
write("</p>");
write("<p id=\"p3_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>428<br></b></nobr>");
write("</p>");
write("<p id=\"p3_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>429<br></b></nobr>");
write("</p>");
write("<p id=\"p3_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:458px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>430<br></b></nobr>");
write("</p>");
write("<p id=\"p3_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-116px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>USB ADAPTER UNIT (32−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-122px;top:513px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-116px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (32−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-122px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:101px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>The shielded wires have a heat−shrink tube <br>insulating the outside of the wire. <br>The color of the insulating tube, <br>typically black or dark gray, <br>may not match the color of the wire <br>shown on the circuit diagram.<br></b></nobr>");
write("</p>");
write("<p id=\"p3_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-313px;top:82px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (10 A)<br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-402px;top:82px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (10 A)<br>FUSE <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-221px;top:82px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC CUT <br>RELAY <br>(8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-132px;top:82px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC CUT <br>RELAY <br>(4−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:83px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (7.5 A)<br>FUSE <br>(4−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:83px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 7 (7.5 A)<br>FUSE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-306px;top:483px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT <br>(32−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:212px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>MICU <br>(14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:479px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM <br>(11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:483px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GAUGE <br>CONTROL MODULE <br>(12−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:483px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE CONTROL UNIT <br>(32−A, B, C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}