with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SJA9EFK000000000000EBA208.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:46px;font-weight:normal;font-size:7.08pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:236px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:245px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>OPDS UNIT (36−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:236px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POP−UP HOOD UNIT (26−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RIGHT TAILLIGHT (19−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>GLOVE BOX LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT (33−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER SWITCH LIGHT (28−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT ASHTRAY LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CONSOLE BOX LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>SELECT/RESET/INFORMATION SWITCH (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT (Light) (31−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:449px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>POWER MIRROR SWITCH LIGHT (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:636px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (ETCSRLY) (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CABLE REEL (Steering switches lights) (23−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:591px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>THROTTLE ACTUATOR CONTROL MODULE (11−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:352px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT (33−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT TAILLIGHT (19−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:556px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (32−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S POCKET LIGHT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HAZARD WARNING SWITCH LIGHT (19−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:334px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:343px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:352px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:467px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:565px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:520px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:476px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:485px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:547px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:423px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:511px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:449px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:556px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:290px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ECPS CONTROL UNIT (25−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:325px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:449px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>NAVIGATION UNIT (33−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AUDIO UNIT (32−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:423px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>INTERFACE DIAL (32−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACTIVE NOISE CANCELLATION FRONT MICROPHONE (32−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:533px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 31 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:542px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PCM (STRLD) (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:657px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 32 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:542px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:667px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:237px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:449px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:423px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:414px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:733px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION SWITCH (21−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>CIGARETTE LIGHTER LIGHT (9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:387px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>HEADLIGHT WASHER SWITCH LIGHT (21−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:502px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:263px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>217<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:388px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>207<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:521px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>202<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:645px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>266<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:290px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>294<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:326px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>192<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:414px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>295<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:543px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>274<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:667px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>296<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:440px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACTIVE NOISE CANCELLATION REAR MICROPHONE (32−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DISPLAY UNIT (33−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:458px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-71px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:250px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>293<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:250px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>LEFT SIDE SEAT BELT TENSION REDUCER SOLENOID (36−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:423px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>AFS OFF/VSA OFF SWITCH LIGHT (13−A) (24−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-433px;top:180px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 10 (7.5 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-433px;top:260px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 4 (15 A) <br>FUSE <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-363px;top:517px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 1 (15 A) <br>FUSE <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-435px;top:561px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>PGM−FI <br>MAIN RELAY 1 <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-287px;top:557px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>THROTTLE ACTUATOR <br>CONTROL MODULE <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:529px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>SEAT HEATER SWITCH LIGHT (28−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-434px;top:672px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 13 (15 A) <br>FUSE <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:396px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>A/T GEAR POSITION <br>INDICATOR PANEL LIGHT (9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:237px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>No. 21 (10 A) <br>FUSE <br>(6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:322px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX <br>(5−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:369px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>ACC RELAY <br>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:535px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DRIVER'S <br>UNDER−DASH FUSE/RELAY BOX <br>(7−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:494px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (ST) <br>(6−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:619px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>STARTER <br>CUT RELAY 1 <br>(7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:432px;font-weight:normal;font-size:4.25pt;\">");
write("<nobr><b>DASH LIGHTS BRIGHTNESS <br>CONTROLLER LIGHTS (13−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:657px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:533px;font-weight:normal;font-size:3.54pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}